/**
 * The shipped card computes no history of its own (T7-18).
 *
 * This reads `dist/glt-flow-card.js`, not `src/`. Phase 5 found retirements
 * that existed only in files nobody ships while the same defect ran live in the
 * artifact, and that is why the assertion is against the generated bytes.
 *
 * **A grep is necessary here and it is not sufficient, and this file should not
 * let a reader believe otherwise.** Phase 6's `shipped-alarm-truth.test.mjs`
 * passed for the whole life of a defect: `alarms/list` did appear in the bytes,
 * in the one place nothing else reached, and three surfaces reported a confident
 * zero. A grep can see that a call exists. It cannot see whether anything
 * reaches it.
 *
 * The outcome half is plan 07-19, which renders each surface, opens nothing and
 * reads the number. Neither assertion replaces the other.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const ARTIFACT = new URL("../dist/glt-flow-card.js", import.meta.url);
const source = readFileSync(ARTIFACT, "utf8");

/** Return the brace-balanced body of a named function in the artifact. */
function functionBody(text, declaration) {
  const start = text.indexOf(declaration);
  if (start < 0) return null;
  const open = text.indexOf("{", start + declaration.length - 1);
  let depth = 0;
  for (let index = open; index < text.length; index += 1) {
    if (text[index] === "{") depth += 1;
    else if (text[index] === "}") {
      depth -= 1;
      if (depth === 0) return text.slice(open, index + 1);
    }
  }
  return null;
}

/** Strip comments, so a docstring quoting a retired call is not read as one. */
function code(body) {
  return body
    .replaceAll(/\/\*[\s\S]*?\*\//g, " ")
    .replaceAll(/\/\/[^\n]*/g, " ");
}

/**
 * Retirements that reach the artifact, and what each must no longer do.
 *
 * These four are referenced by something the bundle includes, so "reachable and
 * inert" is a property the shipped bytes can actually carry.
 */
const RETIRED_IN_ARTIFACT = [
  ["aggregateSeries", "function aggregateSeries(", [/Math\.floor/, /bucket/i]],
  ["trendCsv", "function trendCsv(", [/Math\.abs/, /download/]],
  ["reportCsv", "function reportCsv(", [/_display/, /csvCell/]],
  ["printReport", "function printReport(", [/window\.open/, /document\.write/]],
];

/**
 * Retirements the bundler removes, and why that is not a gap in the assertion.
 *
 * `integrateEnergy` and `energySummary` are module-level exports of `core.mjs`
 * that nothing in the bundle imports, so esbuild drops them. **"Reachable and
 * inert" is not a property the artifact can carry for an export nothing
 * references**, and pretending otherwise would mean adding a fake reference to
 * keep a dead function alive so a test could assert it does nothing.
 *
 * So the claim for these two is *absence*, which is weaker on its own -- and it
 * is exactly the weakness the pattern was written to avoid. What makes it
 * sufficient here is that the replacement is asserted separately, in the
 * Companion suite, against behaviour: `test_energy_counters.py` and
 * `test_energy_units.py` prove the arithmetic that took over. The pattern's
 * warning is about proving the absence of something *nothing checks*; these are
 * checked, elsewhere and by name.
 */
const REMOVED_BY_BUNDLER = ["integrateEnergy", "energySummary"];

test("every retired evaluator that ships is present and computes nothing", () => {
  for (const [name, declaration, forbidden] of RETIRED_IN_ARTIFACT) {
    const body = functionBody(source, declaration);
    assert.ok(
      body !== null,
      `${name} is gone from the artifact; it must stay reachable and inert, or ` +
      "there is nothing left to assert about",
    );
    const stripped = code(body);
    for (const pattern of forbidden) {
      assert.ok(
        !pattern.test(stripped),
        `${name} still reaches ${pattern} in the shipped bytes`,
      );
    }
  }
});

test("the evaluators the bundler removes are absent rather than live", () => {
  for (const name of REMOVED_BY_BUNDLER) {
    const body = functionBody(source, `function ${name}(`);
    if (body === null) continue;
    // Present after all -- something started importing it. Then the stronger
    // claim applies and it must be inert.
    const stripped = code(body);
    assert.ok(
      !/price_per_unit|co2_factor|3600000/.test(stripped),
      `${name} is back in the artifact and still computing`,
    );
  }
});

test("the shipped card issues no Recorder request of its own", () => {
  // D5. Every history read was a browser callApi straight to history/period,
  // so the project policy never saw one and no export was audited.
  const body = functionBody(source, "async _ensureHistory(");
  assert.ok(body !== null, "_ensureHistory is gone rather than retired");
  const stripped = code(body);
  assert.ok(!/callApi/.test(stripped), "_ensureHistory still calls callApi");
  assert.ok(!/history\/period/.test(stripped), "_ensureHistory still names history/period");

  // And nowhere else in the artifact, either -- retiring the one caller would
  // not help if another path had grown its own.
  const wholeCode = code(source);
  assert.ok(
    !/callApi\(\s*["']GET["']\s*,\s*[`"']history\//.test(wholeCode),
    "some path in the artifact still reaches the Recorder directly",
  );
});

// The other half of the retirement -- that the artifact reaches the Companion's
// history routes -- is asserted by plan 07-18, which builds the surfaces that
// call them. Asserting it here would be red for a reason that has nothing to do
// with whether the retirement worked, and a test that is red for the wrong
// reason teaches its reader to ignore it.
