"""The bucket grid a named window should produce.

Phase 7 closed with `history/coverage` and `history/export` deliberately unbuilt,
because coverage needs this grid and the grid's bucket step is a decision rather
than a derivation. This is that decision, made explicitly and proven.

Two things are asserted here, and the second is what stops the first from being
circular. The corpus was generated by `expected_instants`, so replaying it
against `expected_instants` proves only that the function is deterministic. The
invariants below are computed independently of it -- from the elapsed time
between instants, from the calendar, and from the resolved span -- so an
implementation that is self-consistently wrong fails them.
"""
from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone as _timezone
from pathlib import Path

import pytest

from custom_components.glt_flow_card import period_resolution

CORPUS = json.loads(
    (Path(__file__).parent / "fixtures" / "instant_grid_corpus.json").read_text(encoding="utf-8")
)


def test_the_corpus_is_reproduced_exactly():
    """Every committed grid is reproduced byte for byte."""
    assert CORPUS["cases"], "the instant-grid corpus is empty"
    for case in CORPUS["cases"]:
        produced = period_resolution.expected_instants(
            case["spec"], now=case["now"], timezone=case["timezone"],
        )
        assert produced == case["expected_instants"], (
            f"{case['spec']} in {case['timezone']} at {case['now']}: {case['why']}"
        )
        assert period_resolution.canonical_grid(case["spec"], produced) == case["canonical"]


def test_hourly_grids_step_by_one_elapsed_hour():
    """An hour is a duration, so consecutive hourly instants are 3600 s apart.

    Computed from the instants themselves rather than from the step that made
    them. This is the assertion a wall-clock implementation fails: adding one
    hour to a local time across a fall-back transition produces two instants
    with the same wall clock and two elapsed hours between them.
    """
    checked = 0
    for case in (c for c in CORPUS["cases"] if c["step"] == "hour"):
        moments = [datetime.fromisoformat(text) for text in case["expected_instants"]]
        for earlier, later in zip(moments, moments[1:]):
            assert later - earlier == timedelta(hours=1), (
                f"{case['spec']} in {case['timezone']}: {earlier} -> {later} is not one hour"
            )
            checked += 1
    assert checked > 0, "no hourly grid was examined"


def test_calendar_grids_land_on_local_midnight():
    """Daily and monthly buckets are calendar steps, so each starts at 00:00.

    A constant 86 400 000 ms step passes for most of the year and puts 23:00 or
    01:00 in the list exactly twice, which is the failure this catches.
    """
    checked = 0
    for case in (c for c in CORPUS["cases"] if c["step"] in ("day", "month")):
        for text in case["expected_instants"]:
            moment = datetime.fromisoformat(text)
            assert (moment.hour, moment.minute, moment.second) == (0, 0, 0), (
                f"{case['spec']} in {case['timezone']}: {text} is not local midnight"
            )
            if case["step"] == "month":
                assert moment.day == 1, f"{text} is not the first of a month"
            checked += 1
    assert checked > 0, "no calendar grid was examined"


def test_the_grid_covers_the_window_and_does_not_overrun_it():
    """Every instant lies inside the resolved window, and the last one is inside it.

    An off-by-one that appends the window's end would report one bucket more
    than the Recorder can ever return, so every complete answer would show a gap.
    """
    for case in CORPUS["cases"]:
        resolved = period_resolution.resolve(
            case["spec"], now=case["now"], timezone=case["timezone"],
        )
        start = datetime.fromisoformat(resolved["start"])
        end = datetime.fromisoformat(resolved["end"])
        moments = [datetime.fromisoformat(text) for text in case["expected_instants"]]
        assert moments[0] == start, f"{case['spec']}: the grid does not begin at the window start"
        assert moments[-1] < end, f"{case['spec']}: the grid overruns the window end"
        assert moments == sorted(moments), f"{case['spec']}: the grid is not ordered"
        assert len(set(moments)) == len(moments), f"{case['spec']}: the grid repeats an instant"


@pytest.mark.parametrize(
    ("spec", "now", "timezone", "count", "span"),
    [
        # The numbers the whole phase turns on, asserted as literals so that a
        # regression has to change a number a human wrote rather than a number
        # the code produced.
        ("day", "2027-03-28T12:00:00+00:00", "Europe/Berlin", 23, 23),
        ("day", "2027-10-31T12:00:00+00:00", "Europe/Berlin", 25, 25),
        ("day", "2027-06-15T12:00:00+00:00", "Europe/Berlin", 24, 24),
        # 31 daily buckets, but 745 elapsed hours -- the pair that shows why the
        # window and the bucket cannot be derived from each other.
        ("month", "2027-10-15T12:00:00+00:00", "Europe/Berlin", 31, 745),
        ("month", "2027-03-15T12:00:00+00:00", "Europe/Berlin", 31, 743),
        ("year", "2027-05-05T12:00:00+00:00", "Europe/Berlin", 12, 8760),
        # A rolling window is a duration: 24 hours even on a 25-hour calendar day.
        ("rolling-24h", "2027-10-31T12:00:00+00:00", "Europe/Berlin", 24, 24),
    ],
)
def test_the_load_bearing_numbers(spec, now, timezone, count, span):
    instants = period_resolution.expected_instants(spec, now=now, timezone=timezone)
    resolved = period_resolution.resolve(spec, now=now, timezone=timezone)
    assert len(instants) == count
    assert resolved["span_hours"] == span


def test_an_unknown_period_is_refused_rather_than_defaulted():
    """A grid for "sometimes" would be a grid for a day, silently."""
    with pytest.raises(ValueError, match="unknown_period"):
        period_resolution.bucket_for("sometimes")
    with pytest.raises(ValueError, match="unknown_period"):
        period_resolution.expected_instants("sometimes", now="2027-06-01T00:00:00+00:00", timezone="UTC")


def test_every_named_period_has_a_bucket_step():
    """A spec without a step would resolve a window nothing could measure."""
    assert set(period_resolution.BUCKET_STEPS) == set(period_resolution.SPECS), (
        "a named period exists that no bucket step covers, or vice versa"
    )
    for step in period_resolution.BUCKET_STEPS.values():
        assert step in period_resolution.BUCKET_MODELS
