/**
 * The English catalog.
 *
 * Every user-facing English string the browser renders, in one sorted, flat
 * table of `namespace.name` keys. Values carry named `{placeholder}`
 * templates rather than being functions, because a function cannot be supplied
 * as data — and a locale that cannot be supplied as data is a code edit, which
 * is exactly what I18N-01 says a locale must not be.
 *
 * Sorted, so a diff shows what changed rather than where it was inserted.
 */
import { registerCatalog } from "./catalog-lookup.mjs";

export const ENTRIES = Object.freeze({
  "alarms.acknowledge": "Acknowledge",
  "alarms.alarms_title": "Alarms",
  "alarms.attempts_title": "Delivery attempts",
  "alarms.binding_read_only": "Read-only",
  "alarms.cancel": "Cancel",
  "alarms.comment": "Comment",
  "alarms.confirm": "OK",
  "alarms.delivery_failed": "Delivery failed",
  "alarms.delivery_none": "No notification targets configured; alarms are annunciated here only",
  "alarms.links_title": "Context",
  "alarms.no_alarms": "No active alarms",
  "alarms.preview_ambiguous": "occurs twice on",
  "alarms.preview_ambiguous_tail": "this entry runs once, at",
  "alarms.preview_nonexistent": "does not exist on",
  "alarms.preview_nonexistent_tail": "this entry will not run",
  "alarms.preview_normal": "runs at",
  "alarms.priority_critical": "Critical",
  "alarms.priority_info": "Information",
  "alarms.priority_warning": "Warning",
  "alarms.schedule_kind_instant": "Runs at a time",
  "alarms.schedule_kind_interval": "Operating period",
  "alarms.schedule_preview": "Effective times",
  "alarms.schedule_title": "Schedules",
  "alarms.setting_default": "default",
  "alarms.settings_title": "Alarm settings",
  "alarms.shelve": "Shelve",
  "alarms.shelve_minutes": "Suppress for how many minutes?",
  "alarms.shelve_too_long": "Longer than this site allows",
  "alarms.state_acknowledged": "acknowledged",
  "alarms.state_active": "active",
  "alarms.state_indeterminate": "state unknown",
  "alarms.state_returned": "returned",
  "alarms.state_suppressed": "suppressed",
  "alarms.suppressed_acknowledged": "acknowledged",
  "alarms.suppressed_by": "by",
  "alarms.suppressed_maintenance": "in maintenance",
  "alarms.suppressed_shelved": "shelved",
  "alarms.suppressed_until": "until",
  "assets.attachment_limits": "At most {count} attachments, each up to {megabytes} MB.",
  "assets.column_declared_in": "Declared in",
  "assets.column_diagnosis": "Diagnosis",
  "assets.column_evidence": "Evidence",
  "assets.column_note": "Note",
  "assets.column_provenance": "Provenance",
  "assets.column_reference": "Reference",
  "assets.column_slot": "Slot",
  "assets.column_tick": "Tick",
  "assets.column_value": "Value",
  "assets.diagnosis_duplicate_binding": "duplicate binding",
  "assets.diagnosis_missing": "missing",
  "assets.diagnosis_present": "present",
  "assets.diagnosis_registered_not_loaded": "registered but not loaded",
  "assets.diagnosis_service_missing": "service missing",
  "assets.diagnosis_stale": "stale",
  "assets.diagnosis_unregistered": "no registry entry",
  "assets.diagnosis_wrong_device_class": "wrong device class",
  "assets.diagnosis_wrong_unit": "wrong unit",
  "assets.field_asset": "Asset",
  "assets.field_note": "Note",
  "assets.field_reason": "Reason",
  "assets.field_title": "Task",
  "assets.measured": "measured",
  "assets.no_entries": "No entries.",
  "assets.read_only": "This view changes nothing. Every remediation is a link, not an action.",
  "assets.refused_simulating": "Not performed: a simulation is running.",
  "assets.refused_unknown": "Not performed: the simulation state could not be determined. Please try again.",
  "assets.session_active": "Simulation active — started by {who}, ends {until}. The plant is not being operated.",
  "assets.session_expired": "The simulation has expired. The plant is being operated again.",
  "assets.simulated": "simulated",
  "assets.simulated_shape": "◈",
  "catalog.catalog_title": "Symbol catalog",
  "catalog.direction_bidirectional": "Both ways",
  "catalog.direction_in": "Inlet",
  "catalog.direction_out": "Outlet",
  "catalog.filter_all": "All",
  "catalog.filter_category": "Category",
  "catalog.filter_domain": "Domain",
  "catalog.filter_style": "Style",
  "catalog.filter_text": "Search",
  "catalog.kind_power": "Power",
  "catalog.kind_process": "Process",
  "catalog.kind_signal": "Signal",
  "catalog.multiplicity_full": "At its limit",
  "catalog.multiplicity_many": "Many connections",
  "catalog.multiplicity_one": "One connection",
  "catalog.no_matches": "No symbol matches these filters",
  "catalog.port_direction": "Direction",
  "catalog.port_kind": "Kind",
  "catalog.port_medium": "Medium",
  "catalog.port_multiplicity": "Connections",
  "catalog.port_side": "Side",
  "catalog.published_variants": "published variants",
  "catalog.refusal_direction_conflict": "The directions conflict: both ports point the same way.",
  "catalog.refusal_duplicate_connection": "These two ports are already connected.",
  "catalog.refusal_kind_mismatch": "The kinds differ: a process port cannot join a signal or power port.",
  "catalog.refusal_medium_mismatch": "The media differ: these two ports carry different things.",
  "catalog.refusal_multiplicity_exceeded": "That port already has the one connection it admits.",
  "catalog.refusal_self_connection": "A port cannot be connected to itself.",
  "catalog.refusal_title": "This connection is not possible",
  "catalog.refusal_unknown": "The connection was refused.",
  "contract.dangling_reference": "A reference to {id} in {collection} points at nothing",
  "contract.depth": "Nesting too deep: {actual}, at most {limit}",
  "contract.duplicate_id": "The id {id} appears more than once in {collection}",
  "contract.error_limit": "{actual} findings; only the first {limit} are shown",
  "contract.id_length": "Id too long: {actual} characters, at most {limit}",
  "contract.json_bytes": "Project too large: {actual} bytes, at most {limit}",
  "contract.nodes": "Too many elements: {actual}, at most {limit}",
  "contract.path_length": "Path too long: {actual} characters, at most {limit}",
  "contract.required": "Required field missing: {property}",
  "contract.schema_version": "Schema version {actual} is not supported. Allowed: {allowed}",
  "contract.string_bytes": "Text too long: {actual} bytes, at most {limit}",
  "contract.type": "Wrong data type — {expected} expected",
  "contract.type_keyword": "The value breaks the {keyword} rule",
  "contract.unknown": "Unknown finding: {code}",
  "designer.add": "Add object",
  "designer.align": "Align",
  "designer.canvas_label": "Designer canvas",
  "designer.confirm_delete": "Delete the selected objects?",
  "designer.confirm_remove_pack": "Remove this extension pack?",
  "designer.conflict": "Conflict",
  "designer.connect": "Connect ports",
  "designer.connect_choose_source": "Choose the source port",
  "designer.connect_choose_target": "Choose the target port",
  "designer.connect_refused": "Connection refused",
  "designer.contributes": "Contributes",
  "designer.delete": "Delete",
  "designer.disconnect": "Disconnect",
  "designer.distribute": "Distribute",
  "designer.extend_selection": "Extend selection",
  "designer.extensions": "Installed extensions",
  "designer.group": "Group",
  "designer.instantiate_master": "Place master instance",
  "designer.keyboard_help": "Keyboard",
  "designer.layer_hidden": "Hidden",
  "designer.layer_locked": "Locked",
  "designer.layer_unlocked": "Unlocked",
  "designer.layer_visible": "Visible",
  "designer.layers": "Layers",
  "designer.minimap_label": "Diagram overview",
  "designer.no_extensions": "No extension packs are installed",
  "designer.nothing_selected": "Nothing selected",
  "designer.nudge_coarse": "Nudge, coarse",
  "designer.nudge_fine": "Nudge",
  "designer.objects": "objects",
  "designer.ready": "Ready",
  "designer.redo": "Redo",
  "designer.reorder": "Bring forward",
  "designer.resize": "Resize",
  "designer.select": "Select",
  "designer.supports": "Supports project schema",
  "designer.undo": "Undo",
  "designer.undo_depth": "Undo steps kept",
  "designer.ungroup": "Ungroup",
  "designer.viewport": "Current view",
  "equipment.command_failed": "Command failed",
  "equipment.command_pending": "Command pending",
  "equipment.communication_error": "Communication error",
  "equipment.fault": "Fault",
  "equipment.interlock": "Interlocked",
  "equipment.invalid": "Invalid value",
  "equipment.local": "Local control",
  "equipment.locked": "Locked",
  "equipment.maintenance": "Maintenance",
  "equipment.manual": "Manual",
  "equipment.off": "Off",
  "equipment.running": "Running",
  "equipment.stale": "Value not current",
  "equipment.standby": "Standby",
  "equipment.unknown": "Unknown",
  "equipment.warning": "Warning",
  "legacy.ack_via_alarm_list": "Acknowledgement happens through the alarm list.",
  "legacy.alarm_state_unavailable": "Alarm state is currently unavailable.",
  "legacy.auto_connect": "Connect automatically",
  "legacy.auto_mapping": "Auto mapping",
  "legacy.button_energy": "⚡ Energy",
  "legacy.button_reports": "▤ Reports",
  "legacy.button_z_lower": "Send backward",
  "legacy.button_z_raise": "Bring forward",
  "legacy.category_air": "Air handling / ventilation",
  "legacy.category_building": "Building",
  "legacy.category_cooling": "Cooling",
  "legacy.command_failed": "Command failed",
  "legacy.command_running": "Command running",
  "legacy.confirm_delete_project": "Really delete this project?",
  "legacy.controls_via_server": "Operation runs through the object controls the server assembles.",
  "legacy.custom_image_optional": "Custom image / SVG (optional)",
  "legacy.download_yaml": "Download YAML",
  "legacy.entities_export": "Export entities from Home Assistant",
  "legacy.entities_hint": "Without a Home Assistant connection: export in HA, import here — entity fields then offer suggestions.",
  "legacy.entities_import": "Import entities (.json)",
  "legacy.entities_imported": "Imported entities",
  "legacy.entities_invalid": "File unreadable — expected shape: glt-flow-card-entities JSON.",
  "legacy.entities_offline": "No Home Assistant connected — the import uses the stored list.",
  "legacy.entities_rejected": "rejected",
  "legacy.entity": "Entity",
  "legacy.entity_missing": "Entity missing",
  "legacy.fault": "Fault",
  "legacy.fit_view": "Fit view",
  "legacy.fullscreen": "Fullscreen",
  "legacy.height": "Height",
  "legacy.loading_entities": "Loading Home Assistant entities",
  "legacy.lock_released": "Lock released.",
  "legacy.lovelace_yaml": "Lovelace YAML",
  "legacy.main_entity": "Main entity",
  "legacy.medium_air_exhaust": "Exhaust air",
  "legacy.medium_air_extract": "Extract air",
  "legacy.medium_air_outdoor": "Outdoor air",
  "legacy.medium_air_supply": "Supply air",
  "legacy.medium_cold_water": "Cold water",
  "legacy.medium_cooling_return": "Chilled water return",
  "legacy.medium_cooling_supply": "Chilled water",
  "legacy.medium_dhw": "Hot water",
  "legacy.medium_electrical": "Electrical",
  "legacy.medium_heating_return": "Return",
  "legacy.medium_heating_supply": "Flow",
  "legacy.medium_neutral": "Medium",
  "legacy.medium_source": "Source",
  "legacy.menu": "Menu",
  "legacy.menu_operation": "Operations",
  "legacy.menu_style": "Style",
  "legacy.menu_view": "View",
  "legacy.meter": "Meter",
  "legacy.migration_workflow": "Migration workflow",
  "legacy.nav_alarms": "Alarms",
  "legacy.nav_automap": "Auto mapping",
  "legacy.nav_cad": "CAD",
  "legacy.nav_diagnostics": "Diagnostics",
  "legacy.nav_energy": "Energy",
  "legacy.nav_entities": "Entities",
  "legacy.nav_maintenance": "Maintenance",
  "legacy.nav_operations": "Operations",
  "legacy.nav_project": "Project v1",
  "legacy.nav_schedule": "Schedules",
  "legacy.nav_semantics": "Semantics",
  "legacy.nav_simulation": "Simulation",
  "legacy.nav_symbols": "Symbols 300+",
  "legacy.nav_templates": "Templates",
  "legacy.nav_trends": "Trends",
  "legacy.new_project_name": "Name for the new project",
  "legacy.no_date": "No date",
  "legacy.no_energy_meters": "No energy meters configured.",
  "legacy.no_fault": "No fault",
  "legacy.no_work_orders": "No work orders.",
  "legacy.open_detail": "Open detail view",
  "legacy.own_image": "Own image",
  "legacy.paste_compare_json": "Paste the comparison configuration as JSON",
  "legacy.perform_maintenance": "Perform maintenance",
  "legacy.project_locked": "Project locked.",
  "legacy.prompt_group_name": "Group name",
  "legacy.prompt_layer_name": "Layer name",
  "legacy.prompt_period": "Period: day / week / month / year",
  "legacy.prompt_project_name": "Project name",
  "legacy.prompt_report_name": "Report name",
  "legacy.prompt_task": "Task",
  "legacy.prompt_template_name": "Template name",
  "legacy.redo": "Redo",
  "legacy.report_designer": "Report designer",
  "legacy.report_format_hint": "Report: 'csv' for CSV or 'pdf' for print/PDF",
  "legacy.running": "Running",
  "legacy.save_as": "Save as",
  "legacy.schedule_hint": "Automatic (e.g. 1 07:00) or empty",
  "legacy.search_component": "Search component or symbol…",
  "legacy.select_equipment_first": "Select a plant object first.",
  "legacy.select_something_first": "Select a component, data point, path or KPI first.",
  "legacy.select_two_first": "Select at least two elements with Ctrl/Shift.",
  "legacy.simulated_value": "Simulated value",
  "legacy.sponsor": "Sponsor",
  "legacy.sponsor_free": "Everything is free — sponsoring is voluntary.",
  "legacy.sponsor_hint": "everything is free · ♥ sponsoring is voluntary",
  "legacy.state_entity": "State entity",
  "legacy.style_clean_light": "Clean / Modern Light",
  "legacy.subplant_saved": "Sub-plant saved as a template.",
  "legacy.subtitle": "Building management · live plant view",
  "legacy.suppress_minutes": "Suppress for how many minutes?",
  "legacy.symbol_ahu": "Air handling unit",
  "legacy.symbol_air_filter": "Air filter",
  "legacy.symbol_balancing_valve": "Balancing valve",
  "legacy.symbol_battery": "Battery storage",
  "legacy.symbol_boiler": "Boiler",
  "legacy.symbol_buffer_layered": "Stratified buffer tank",
  "legacy.symbol_buffer_vertical": "Buffer tank · Vertical",
  "legacy.symbol_check_valve": "Check valve",
  "legacy.symbol_chiller": "Chiller",
  "legacy.symbol_co2_sensor": "CO₂ sensor",
  "legacy.symbol_cooling_buffer": "Chilled water buffer",
  "legacy.symbol_cooling_coil": "Cooling coil",
  "legacy.symbol_cooling_tower": "Cooling tower",
  "legacy.symbol_custom_image": "Custom symbol / image",
  "legacy.symbol_damper": "Damper",
  "legacy.symbol_dhw_tank": "Domestic hot water tank",
  "legacy.symbol_expansion_vessel": "Expansion vessel",
  "legacy.symbol_fan_extract": "Extract air fan",
  "legacy.symbol_fan_supply": "Supply air fan",
  "legacy.symbol_fancoil": "Fan coil unit",
  "legacy.symbol_fancoil_cooling": "Fan coil",
  "legacy.symbol_filter_water": "Strainer",
  "legacy.symbol_flow_sensor": "Flow",
  "legacy.symbol_generic_machine": "Generic plant item",
  "legacy.symbol_grid": "Grid",
  "legacy.symbol_heat_exchanger_plate": "Plate heat exchanger",
  "legacy.symbol_heat_pump_compact": "Heat pump · Compact",
  "legacy.symbol_heat_pump_neo": "Heat pump · Neo",
  "legacy.symbol_heating_circuit": "Heating circuit",
  "legacy.symbol_heating_coil": "Heating coil",
  "legacy.symbol_humidifier": "Humidifier",
  "legacy.symbol_humidity_sensor": "Humidity sensor",
  "legacy.symbol_hydraulic_separator": "Hydraulic separator",
  "legacy.symbol_immersion_heater": "Immersion heater",
  "legacy.symbol_manifold": "Manifold",
  "legacy.symbol_meter": "Energy meter",
  "legacy.symbol_mixing_valve": "Mixing valve",
  "legacy.symbol_pressure_sensor": "Pressure sensor",
  "legacy.symbol_pump_circulation": "Circulator pump",
  "legacy.symbol_pump_dhw": "Hot water circulation pump",
  "legacy.symbol_pump_inline": "Pump · Inline",
  "legacy.symbol_pv_array": "PV array",
  "legacy.symbol_radiator": "Radiator",
  "legacy.symbol_room_air": "Room / zone",
  "legacy.symbol_room_sensor": "Room sensor",
  "legacy.symbol_solar_thermal": "Solar thermal",
  "legacy.symbol_source_ground": "Ground loop / source",
  "legacy.symbol_temp_sensor": "Temperature sensor",
  "legacy.symbol_underfloor": "Underfloor heating",
  "legacy.symbol_valve_2way": "Two-way valve",
  "legacy.symbol_valve_3way": "Three-way valve",
  "legacy.symbol_wallbox": "Wallbox",
  "legacy.templates_factory": "Factory templates",
  "legacy.templates_hint": "Loading replaces the current configuration — undo is available. Entities stay empty and are assigned afterwards.",
  "legacy.templates_load": "Load",
  "legacy.templates_none": "No own templates saved yet.",
  "legacy.templates_own": "Your templates",
  "legacy.trend_chart": "Trend chart",
  "legacy.undo": "Undo",
  "legacy.value1_entity": "Value 1 entity",
  "legacy.value1_label": "Value 1 label",
  "legacy.value2_entity": "Value 2 entity",
  "legacy.value2_label": "Value 2 label",
  "legacy.value_invalid": "Value invalid",
  "legacy.value_stale": "Value stale",
  "legacy.x_in_view": "X in view",
  "legacy.y_in_view": "Y in view",
  "legacy.zoom_in": "Zoom in",
  "legacy.zoom_out": "Zoom out",
  "operations.affordance_audit": "Open trusted audit",
  "operations.affordance_cancel": "Cancel",
  "operations.affordance_dismiss": "Dismiss",
  "operations.affordance_state": "Show current state",
  "operations.history_unavailable": "Trends are not available yet",
  "operations.last_updated": "Last updated",
  "operations.no_alarms": "No alarms",
  "operations.no_controls_available": "No controls available to you",
  "operations.no_values_declared": "No values declared",
  "operations.outcome_accepted": "Accepted — awaiting dispatch",
  "operations.outcome_cancelled": "Cancelled — not sent",
  "operations.outcome_confirmed": "Confirmed",
  "operations.outcome_denied": "Not permitted",
  "operations.outcome_dispatched": "Sent — awaiting confirmation",
  "operations.outcome_failed_after_dispatch": "Failed after dispatch — effect unknown",
  "operations.outcome_failed_before_dispatch": "Failed — not sent",
  "operations.outcome_result_unknown": "Effect unknown",
  "operations.outcome_timed_out": "No confirmation — effect unknown",
  "operations.status_live": "Live",
  "operations.status_resyncing": "Reloading",
  "operations.status_stale": "Not live — showing last known values",
  "operations.status_unavailable": "Unavailable",
  "operations.view_not_available": "This view is not available.",
  "period.change": "Consumption",
  "period.circular_mean_required": "This quantity is a direction — an arithmetic mean would be wrong.",
  "period.custom": "Custom range",
  "period.day": "Day",
  "period.entities_exceed_limit": "The query names more entities than the site permits.",
  "period.incompatible_unit": "The unit and the price do not match — they cannot be combined.",
  "period.max": "Maximum",
  "period.mean": "Mean",
  "period.min": "Minimum",
  "period.month": "Month",
  "period.none": "Every sample",
  "period.outside_statistic_coverage": "This period lies before the first recorded value.",
  "period.raw": "from raw values",
  "period.state": "Meter reading",
  "period.statistics": "from long-term statistics",
  "period.unavailable": "unavailable",
  "period.undeclared_meter_model": "This meter does not declare whether it counts or measures.",
  "period.unknown_aggregate": "That aggregate is not known.",
  "period.unknown_period": "That period is not known.",
  "period.unknown_source": "That source is not known.",
  "period.week": "Week",
  "period.window_exceeds_limit": "The window is longer than raw values permit.",
  "period.year": "Year",
  "replay.before_first_sample": "Before the first recorded value",
  "replay.no_recorded_history": "No history recorded",
  "replay.outside_loaded_window": "Outside the loaded window",
  "safety.access_denied": "The access change was refused. Nothing changed.",
  "safety.access_empty": "No member holds a role on this project yet.",
  "safety.access_heading": "Project access",
  "safety.access_loading": "Loading project access",
  "safety.access_revision": "Access revision",
  "safety.access_saved": "Access change applied",
  "safety.acquire_lease": "Acquire editing lease",
  "safety.action_column": "Action",
  "safety.add_member": "Add member",
  "safety.announcements_authority_current": "Server authority refreshed.",
  "safety.announcements_evidence_page_failed": "The next evidence page could not be loaded.",
  "safety.announcements_lease_acquired": "Editing lease acquired by this session.",
  "safety.announcements_lease_held": "Another session is editing.",
  "safety.announcements_lease_released": "Editing lease released.",
  "safety.announcements_lease_renewed": "Editing lease renewed.",
  "safety.apply_access_change": "Apply access change",
  "safety.apply_failure": "Project changes were not applied. Nothing was changed. Review the diagnostic and run a fresh dry run.",
  "safety.apply_selected": "Apply selected changes",
  "safety.apply_success": "Project changes applied",
  "safety.apply_success_body": "Revision {revision} was validated and verified after applying {count} changes. Verified backup {backup_id} remains available.",
  "safety.applying": "Applying {count} project changes",
  "safety.artifact_equality": "Artifact equality",
  "safety.asset_metadata": "Opaque asset metadata",
  "safety.assigned": "Assigned",
  "safety.assignment_column": "Assignment",
  "safety.audit_actor": "Actor",
  "safety.audit_at": "Server time",
  "safety.audit_correlation": "Correlation ID",
  "safety.audit_event": "Event",
  "safety.audit_result": "Result",
  "safety.authority_bar": "Authority state",
  "safety.back_to_overview": "Back to overview",
  "safety.bundle_empty": "No bundle inspected. Project asset metadata is listed without rendering asset content.",
  "safety.bundle_safety": "Bundle safety",
  "safety.byte_identical": "Byte-identical",
  "safety.cancel_access_change": "Cancel access change",
  "safety.cancel_apply": "Cancel project changes",
  "safety.cancel_discard": "Keep my changes",
  "safety.candidate_heading": "Unsaved candidate",
  "safety.candidate_states_applied": "Applied",
  "safety.candidate_states_dirty": "Unsaved changes in this session",
  "safety.candidate_states_none": "No unsaved changes",
  "safety.candidate_states_preserved": "Unsaved changes kept in memory",
  "safety.capabilities_column": "Effective capabilities",
  "safety.capability_codes": "Show capability codes",
  "safety.categories_add": "Added",
  "safety.categories_binding": "Binding",
  "safety.categories_config": "Configuration",
  "safety.categories_move": "Moved",
  "safety.categories_remove": "Removed",
  "safety.check_lease": "Check lease availability",
  "safety.checksum": "SHA-256",
  "safety.choose_user": "Choose an eligible user",
  "safety.client_telemetry": "Client telemetry (untrusted)",
  "safety.close": "Close Project safety",
  "safety.collaboration": "Collaboration",
  "safety.companion": "Companion",
  "safety.companion_states_current": "Authority current",
  "safety.companion_states_incompatible": "Policy version unsupported",
  "safety.companion_states_refreshing": "Refreshing authority",
  "safety.companion_states_stale": "Authority stale",
  "safety.companion_states_unavailable": "Companion unavailable",
  "safety.confirm_access_body": "Change {member} to {role} at access revision {revision}? The change is applied atomically and recorded in the trusted audit.",
  "safety.confirm_access_heading": "Confirm access change",
  "safety.confirm_apply_body": "Apply {count} validated changes to “{project}” at revision {revision}? A verified backup will be created first. This changes project data only and sends no plant command.",
  "safety.confirm_apply_heading": "Confirm project changes",
  "safety.confirm_remove_body": "Remove all access for {member} at access revision {revision}? They keep no role on this project.",
  "safety.conflict_body": "Revision {base} is no longer current; revision {current} is active. Your candidate is kept in memory. Nothing was overwritten.",
  "safety.conflict_choices_discard": "Discard my changes",
  "safety.conflict_choices_merge_preview": "Preview a merge",
  "safety.conflict_choices_refresh": "Refresh from the server",
  "safety.conflict_choices_retry_with_fresh_lease": "Retry with a fresh lease",
  "safety.conflict_heading": "Save blocked — a newer revision exists",
  "safety.connected": "Connected",
  "safety.contract_unknown": "Unknown finding: {code}",
  "safety.control_cancel": "Cancel control",
  "safety.control_confirm_body": "Run “{label}”? The Companion resolves the effect from the current project head; this card sends only the control name and the declared input.",
  "safety.control_confirm_heading": "Confirm configured control",
  "safety.control_correlation": "Correlation ID",
  "safety.control_effect": "Resolved effect",
  "safety.control_heading": "Configured control",
  "safety.control_no_retry": "This card never repeats a control by itself. Decide again if the plant must move.",
  "safety.control_policy": "Control policy",
  "safety.control_preview": "Preview control",
  "safety.control_run": "Run control",
  "safety.control_states_accepted": "Accepted and recorded. Not yet dispatched.",
  "safety.control_states_cancelled_before_dispatch": "Cancelled. Nothing was sent.",
  "safety.control_states_denied": "Denied.",
  "safety.control_states_dispatched": "Dispatched to Home Assistant. Not yet confirmed.",
  "safety.control_states_failed_after_dispatch": "Failed after dispatch. The effect is unknown — check the current state and the trusted audit.",
  "safety.control_states_failed_before_dispatch": "Failed before dispatch. Nothing was sent.",
  "safety.control_states_readback_confirmed": "Confirmed by readback.",
  "safety.control_states_result_unknown": "The result is unknown — check the current state and the trusted audit before acting again.",
  "safety.control_states_timed_out": "Timed out. The effect is unknown — check the current state and the trusted audit.",
  "safety.control_target": "Target",
  "safety.controls_visible": "{count} controls visible to you",
  "safety.current_revision": "Revision",
  "safety.discard_body": "Discard the unsaved changes in this session? They cannot be recovered afterwards.",
  "safety.discard_heading": "Discard unsaved changes",
  "safety.dry_run": "Run dry run",
  "safety.dry_run_fresh": "Run fresh dry run",
  "safety.editing": "Editing",
  "safety.eligible_user": "Eligible user",
  "safety.error_codes_authority_stale": "Server authority is stale. Refresh and try again.",
  "safety.error_codes_capability_denied": "Your role does not permit this action.",
  "safety.error_codes_effect_unknown": "The result is unknown. Check the trusted audit before retrying.",
  "safety.error_codes_feature_unavailable": "This feature is not available in this version.",
  "safety.error_codes_invalid_input": "The request was rejected as invalid. Nothing changed.",
  "safety.error_codes_lease_expired": "The editing lease expired.",
  "safety.error_codes_lease_held": "Another session is editing.",
  "safety.error_codes_lease_required": "An editing lease is required.",
  "safety.error_codes_not_found_or_denied": "This project is not available to you.",
  "safety.error_codes_not_loaded": "The Companion is not loaded.",
  "safety.error_codes_rate_limited": "Too many requests. Wait and try again.",
  "safety.error_codes_revision_conflict": "A newer revision exists. Your candidate is kept.",
  "safety.errors": "Validation issues",
  "safety.exact_card_version": "Exact card version",
  "safety.expected_revision": "Expected",
  "safety.export_telemetry": "Export client telemetry",
  "safety.export_trusted": "Export trusted audit",
  "safety.finding": "Finding",
  "safety.ignored_noise": "Ignored ordering noise",
  "safety.impact": "Impact",
  "safety.inspect_bundle": "Inspect .gltproject bundle",
  "safety.last_refresh": "Last refresh",
  "safety.lease_acquiring": "Requesting exclusive editing lease",
  "safety.lease_expires_in": "Expires in {seconds}s",
  "safety.lease_heading": "Engineering lease",
  "safety.lease_renew_due": "Renewal is due. Renew before the lease expires.",
  "safety.lease_states_available": "Lease available",
  "safety.lease_states_expired": "Lease expired",
  "safety.lease_states_held_other": "Another session is editing",
  "safety.lease_states_held_self": "This session",
  "safety.lease_states_lost": "Lease lost",
  "safety.lease_states_read_only": "Read-only",
  "safety.lease_states_renewing": "Renewing",
  "safety.load_next": "Load next 50 events",
  "safety.manage_access": "Manage project access",
  "safety.media_type": "Media type",
  "safety.member_column": "Member",
  "safety.merge_states_applied": "Merge applied",
  "safety.merge_states_blocked": "The same paths changed on both sides. Choose a different recovery.",
  "safety.merge_states_failed": "The merge preview failed. Your candidate is unchanged.",
  "safety.merge_states_idle": "No merge preview requested.",
  "safety.merge_states_ready": "Merge preview ready. Select the changes to keep.",
  "safety.merge_states_requested": "Requesting merge preview",
  "safety.migration_workflow": "Migration workflow",
  "safety.mode_local": "Local-only project",
  "safety.mode_shared": "Shared project",
  "safety.my_access": "My access",
  "safety.my_role": "My role",
  "safety.never": "Never",
  "safety.no_capabilities": "No capabilities on this project.",
  "safety.no_evidence": "Release evidence is incomplete. Missing or stale gates are listed below.",
  "safety.not_evidence": "Not security or control evidence",
  "safety.not_run": "Not run",
  "safety.overview": "Project safety overview",
  "safety.path": "Path",
  "safety.policy_version": "Policy version",
  "safety.preview_failed": "Migration preview failed. The original project is unchanged. Run a fresh dry run after reviewing the diagnostic.",
  "safety.preview_ready": "Migration preview ready",
  "safety.project": "Project",
  "safety.raw_contract": "Raw contract",
  "safety.read_only": "Read-only",
  "safety.read_only_reasons_authority_absent": "No server authority yet. Shared editing stays read-only until the Companion answers.",
  "safety.read_only_reasons_authority_incompatible": "The Companion uses a policy version this card does not support.",
  "safety.read_only_reasons_authority_loading": "Refreshing server authority. Shared editing is read-only until it returns.",
  "safety.read_only_reasons_authority_rejected": "The Companion refused the authority refresh. Shared editing is read-only.",
  "safety.read_only_reasons_authority_sequence_gap": "An authority update was missed. Refresh before editing.",
  "safety.read_only_reasons_authority_stale": "Server authority is stale. Refresh before editing.",
  "safety.read_only_reasons_companion_disconnected": "The Companion is unavailable. Shared editing is read-only.",
  "safety.read_only_reasons_lease_expired": "The editing lease expired. Your unsaved candidate is kept.",
  "safety.read_only_reasons_lease_lost": "The editing lease was lost. Your unsaved candidate is kept.",
  "safety.read_only_reasons_lease_required": "Acquire the editing lease to make changes.",
  "safety.read_only_reasons_role_missing": "You have no role on this project.",
  "safety.read_only_reasons_role_revoked": "Your role for this project changed. Shared editing is read-only.",
  "safety.release_evidence": "Release evidence",
  "safety.release_lease": "Release editing lease",
  "safety.remove_access": "Remove access",
  "safety.renew_lease": "Renew editing lease",
  "safety.required_dependency": "Required dependency",
  "safety.restore": "Restore verified backup",
  "safety.restore_awaiting": "Enter “{project}” to enable Restore verified backup.",
  "safety.restore_body": "Restore verified backup {backup_id} for “{project}”? The current revision {revision} will be replaced. A new evidence receipt will be created. This changes project data only and sends no plant command.",
  "safety.restore_label": "Enter the project name to confirm",
  "safety.restore_mismatch": "The project name does not match. The project remains unchanged.",
  "safety.restore_ready": "Project name confirmed. Review the revision and backup before continuing.",
  "safety.revision": "Revision",
  "safety.revision_conflict": "Revision {expected} is no longer current; revision {actual} is active. Reload and compare again.",
  "safety.revision_triplet": "Base {base} · Current {current} · Candidate {candidate}",
  "safety.role_column": "Role",
  "safety.role_matrix": "Role capability matrix",
  "safety.role_matrix_unavailable": "The Companion did not return a capability matrix for this role.",
  "safety.role_names_admin": "Admin",
  "safety.role_names_engineer": "Engineer",
  "safety.role_names_none": "No assignment",
  "safety.role_names_operator": "Operator",
  "safety.role_names_viewer": "Viewer",
  "safety.rollback_failure": "Backup restore verification failed. Both snapshots were retained. Download the rollback diagnostic and request administrator recovery.",
  "safety.rollback_running": "Restoring verified backup",
  "safety.rollback_success": "Verified backup restored",
  "safety.rollback_success_body": "Project revision {revision} matches verified backup {backup_id}. A rollback evidence receipt was created.",
  "safety.rows_stale": "The next page could not be loaded. The events shown are no longer current.",
  "safety.schema": "Schema",
  "safety.scope": "Project data only — no Home Assistant service or plant command is executed.",
  "safety.server_authored": "Server-authored",
  "safety.server_normalization": "Server normalization active",
  "safety.shared_authority": "Shared authority",
  "safety.size": "Size",
  "safety.standalone": "Companion unavailable — shared project operations are read-only.",
  "safety.tabs_0": "Overview",
  "safety.tabs_1": "Validate",
  "safety.tabs_2": "Migrate & compare",
  "safety.tabs_3": "Bundles",
  "safety.tabs_4": "Evidence",
  "safety.telemetry_category": "Category",
  "safety.telemetry_empty": "No client telemetry has been recorded in this session.",
  "safety.telemetry_payload": "Payload summary",
  "safety.telemetry_received": "Received",
  "safety.title": "Project safety",
  "safety.trusted_audit": "Trusted audit",
  "safety.trusted_empty": "No trusted audit event is visible to you yet.",
  "safety.unchanged": "Original project unchanged",
  "safety.validate": "Validate project",
  "safety.validation_failed": "Project validation failed",
  "safety.validation_idle": "Choose Validate project to inspect the raw project without changing it.",
  "safety.validation_invalid": "The project is invalid. Review the listed paths; the original remains unchanged.",
  "safety.validation_running": "Validating raw project",
  "safety.validation_success": "Project validation complete",
  "safety.validation_valid": "No validation issues found. The raw project matches schema {version}.",
  "safety.workflow_0": "Inspect",
  "safety.workflow_1": "Preview",
  "safety.workflow_2": "Backup",
  "safety.workflow_3": "Apply",
  "safety.workflow_4": "Verify",
  "sites.age": "read {seconds} s ago",
  "sites.completeness": "{answered} of {total} sites answered",
  "sites.effect_unknown": "Effect unknown — the command may have run. Check the plant state before sending anything again.",
  "sites.missing_sites": "Missing sites:",
  "sites.no_value": "no reading",
  "sites.shape_circuit_open": "✕",
  "sites.shape_healthy": "●",
  "sites.shape_slow": "◐",
  "sites.shape_unreachable": "○",
  "sites.site_circuit_open": "suspended after repeated failures",
  "sites.site_healthy": "reachable",
  "sites.site_slow": "slow",
  "sites.site_unreachable": "unreachable",
  "sites.unverified_tls": "unverified: this site's certificate is not checked",
  "symbols.category_allgemein": "General",
  "symbols.category_brandschutz": "Fire safety",
  "symbols.category_elektro": "Electrical",
  "symbols.category_energie": "Energy",
  "symbols.category_gebaude": "Building",
  "symbols.category_heizung": "Heating",
  "symbols.category_hydraulik": "Hydronics",
  "symbols.category_kalte": "Cooling",
  "symbols.category_rlt": "Air handling",
  "symbols.category_sensorik": "Sensors",
  "symbols.control_enable": "Enable",
  "symbols.control_mode": "Operating mode",
  "symbols.control_open_close": "Open/close",
  "symbols.control_position": "Position",
  "symbols.control_run": "On/off",
  "symbols.control_setpoint": "Setpoint",
  "symbols.control_speed": "Speed",
  "symbols.label": "Heating",
  "symbols.label_brandschutz": "Fire safety",
  "symbols.label_elektro": "Electrical",
  "symbols.label_energie": "Energy",
  "symbols.label_hydraulik": "Hydraulics",
  "symbols.label_k_lte": "Refrigeration",
  "symbols.label_rlt": "Air handling",
  "symbols.label_sensorik": "Instrumentation",
  "symbols.profile_ahu": "Air handling unit",
  "symbols.profile_boiler": "Boiler",
  "symbols.profile_chiller": "Chiller",
  "symbols.profile_damper": "Damper",
  "symbols.profile_dhw_tank": "Domestic hot water tank",
  "symbols.profile_fan": "Fan",
  "symbols.profile_generic": "Generic equipment",
  "symbols.profile_heat_exchanger": "Heat exchanger",
  "symbols.profile_heat_pump": "Heat pump",
  "symbols.profile_meter": "Meter",
  "symbols.profile_mixing_valve": "Three-way mixing valve",
  "symbols.profile_pump": "Pump",
  "symbols.profile_room": "Room / zone",
  "symbols.profile_tank": "Tank",
  "symbols.profile_valve": "Valve",
  "symbols.slot_actual": "Actual flow",
  "symbols.slot_bottom_temp": "Bottom",
  "symbols.slot_co2": "CO₂",
  "symbols.slot_cop": "COP",
  "symbols.slot_extract_flow": "Extract air flow",
  "symbols.slot_extract_temp": "Extract",
  "symbols.slot_feedback": "Feedback",
  "symbols.slot_flow": "Air flow",
  "symbols.slot_flow_temp": "Flow",
  "symbols.slot_hours": "Operating hours",
  "symbols.slot_humidity": "Humidity",
  "symbols.slot_middle_temp": "Middle",
  "symbols.slot_operating_hours": "Operating hours",
  "symbols.slot_position": "Position",
  "symbols.slot_power": "Power",
  "symbols.slot_pressure": "Pressure",
  "symbols.slot_primary_in_temp": "Primary in",
  "symbols.slot_primary_out_temp": "Primary out",
  "symbols.slot_return_temp": "Return",
  "symbols.slot_secondary_in_temp": "Secondary in",
  "symbols.slot_secondary_out_temp": "Secondary out",
  "symbols.slot_setpoint": "Setpoint",
  "symbols.slot_speed": "Speed",
  "symbols.slot_starts": "Starts",
  "symbols.slot_supply_flow": "Supply air flow",
  "symbols.slot_supply_temp": "Supply",
  "symbols.slot_temperature": "Room temperature",
  "symbols.slot_top_temp": "Top",
  "symbols.slot_value": "Value",
  "symbols.style_classic_scada": "Classic SCADA",
  "symbols.style_clean": "Clean",
  "symbols.style_neo2030": "Neo 2030",
  "symbols.style_operations_light": "Operations Light",
  "symbols.style_pid_dark": "P&ID Dark",
  "symbols.style_standard_2d": "Standard 2D",
  "symbols.group_waermepumpen": "Heat pumps",
  "symbols.group_kessel_erzeuger": "Boilers & generators",
  "symbols.group_puffer_speicher": "Buffer storage",
  "symbols.group_heizflaechen": "Heat emitters",
  "symbols.group_solar": "Solar",
  "symbols.group_stationen": "Stations",
  "symbols.group_pumpen": "Pumps",
  "symbols.group_ventile": "Valves",
  "symbols.group_waermetauscher": "Heat exchangers",
  "symbols.group_verteilung": "Distribution",
  "symbols.group_schmutzfaenger": "Strainers",
  "symbols.group_ausdehnung": "Expansion",
  "symbols.group_geraete": "AHU units",
  "symbols.group_ventilatoren": "Fans",
  "symbols.group_klappen_regelung": "Dampers & control",
  "symbols.group_filter": "Filters",
  "symbols.group_register": "Coils",
  "symbols.group_waermerueckgewinnung": "Heat recovery",
  "symbols.group_befeuchtung": "Humidification",
  "symbols.group_schalldaempfer": "Silencers",
  "symbols.group_kaeltemaschinen": "Chillers",
  "symbols.group_komponenten": "Components",
  "symbols.group_kuehler": "Heat rejectors",
  "symbols.group_speicher": "Storage",
  "symbols.group_sole": "Brine",
  "symbols.group_photovoltaik": "Photovoltaics",
  "symbols.group_umwandlung": "Conversion",
  "symbols.group_netz_zaehler": "Grid & metering",
  "symbols.group_laden": "Charging",
  "symbols.group_erzeuger": "Generators",
  "symbols.group_temperatur": "Temperature",
  "symbols.group_druck": "Pressure",
  "symbols.group_durchfluss": "Flow",
  "symbols.group_feuchte": "Humidity",
  "symbols.group_luftqualitaet": "Air quality",
  "symbols.group_raum": "Room",
  "symbols.group_versorgung": "Power supply",
  "symbols.group_schutz_schaltung": "Protection & switching",
  "symbols.group_antriebe": "Drives",
  "symbols.group_meldetechnik": "Fire detection",
  "symbols.group_loeschanlagen": "Suppression",
  "symbols.group_abschottung": "Fire compartment",
  "symbols.symbol_ahu": "Air handling unit",
  "symbols.symbol_air_filter": "Air filter",
  "symbols.symbol_aspirating_detector": "Aspirating smoke detector",
  "symbols.symbol_backflow_preventer": "Backflow preventer",
  "symbols.symbol_balancing_valve": "Balancing valve",
  "symbols.symbol_battery": "Battery storage",
  "symbols.symbol_boiler": "Boiler",
  "symbols.symbol_booster_station": "Pressure booster station",
  "symbols.symbol_brine_station": "Brine station",
  "symbols.symbol_buffer_layered": "Stratified buffer tank",
  "symbols.symbol_burner": "Burner",
  "symbols.symbol_busbar": "Busbar",
  "symbols.symbol_check_valve": "Check valve",
  "symbols.symbol_chiller": "Chiller",
  "symbols.symbol_circuit_breaker": "Circuit breaker",
  "symbols.symbol_cistern": "Rainwater cistern",
  "symbols.symbol_co2_sensor": "CO₂ sensor",
  "symbols.symbol_co2_voc_sensor": "CO₂-VOC sensor",
  "symbols.symbol_cogen_unit": "CHP unit",
  "symbols.symbol_compact_ahu": "Compact AHU",
  "symbols.symbol_compressor": "Compressor",
  "symbols.symbol_condensing_unit": "Condensing unit",
  "symbols.symbol_cooling_buffer": "Chilled water buffer",
  "symbols.symbol_cooling_coil": "Cooling coil",
  "symbols.symbol_cooling_tower": "Cooling tower",
  "symbols.symbol_damper": "Damper",
  "symbols.symbol_dhw_freshwater_station": "Freshwater station",
  "symbols.symbol_dhw_tank": "Domestic hot water tank",
  "symbols.symbol_dirt_separator": "Dirt separator",
  "symbols.symbol_dp_sensor": "Differential pressure sensor",
  "symbols.symbol_dry_cooler": "Dry cooler",
  "symbols.symbol_duct": "Duct section",
  "symbols.symbol_duct_sensor": "Duct sensor",
  "symbols.symbol_ec_fan": "EC fan",
  "symbols.symbol_expansion_vessel": "Expansion vessel",
  "symbols.symbol_extinguishing_system": "Extinguishing system",
  "symbols.symbol_fan_extract": "Extract air fan",
  "symbols.symbol_fan_supply": "Supply air fan",
  "symbols.symbol_filter_water": "Strainer",
  "symbols.symbol_fire_alarm_panel": "Fire alarm panel",
  "symbols.symbol_fire_barrier": "Fire barrier",
  "symbols.symbol_fire_damper": "Fire damper",
  "symbols.symbol_fire_door": "Fire door",
  "symbols.symbol_flat_collector": "Flat plate collector",
  "symbols.symbol_flexible_compensator": "Expansion compensator",
  "symbols.symbol_flow_limiter": "Flow limiter",
  "symbols.symbol_flow_sensor": "Flow sensor",
  "symbols.symbol_flow_switch": "Flow switch",
  "symbols.symbol_flue": "Flue",
  "symbols.symbol_frequency_drive": "Frequency drive",
  "symbols.symbol_frost_thermostat": "Frost thermostat",
  "symbols.symbol_fuel_cell": "Fuel cell",
  "symbols.symbol_gas_sensor": "Gas sensor",
  "symbols.symbol_generator_set": "Standby generator",
  "symbols.symbol_grid": "Grid",
  "symbols.symbol_heat_detector": "Heat detector",
  "symbols.symbol_heat_exchanger_plate": "Plate heat exchanger",
  "symbols.symbol_heat_meter": "Heat meter",
  "symbols.symbol_heat_pump_compact": "Heat pump Compact",
  "symbols.symbol_heat_pump_duo": "Dual heat pump",
  "symbols.symbol_heat_pump_neo": "Heat pump Neo",
  "symbols.symbol_heat_recovery_plate": "Plate heat recovery",
  "symbols.symbol_heat_recovery_rotary": "Rotary heat recovery",
  "symbols.symbol_heating_coil": "Heating coil",
  "symbols.symbol_humidifier": "Humidifier",
  "symbols.symbol_humidity_sensor": "Humidity sensor",
  "symbols.symbol_hybrid_inverter": "Hybrid inverter",
  "symbols.symbol_hydraulic_separator": "Hydraulic separator",
  "symbols.symbol_ice_storage": "Ice storage",
  "symbols.symbol_immersion_heater": "Immersion heater",
  "symbols.symbol_inverter": "Inverter",
  "symbols.symbol_isolator_switch": "Isolator switch",
  "symbols.symbol_kitchen_hood": "Kitchen hood",
  "symbols.symbol_louvre": "Louvre grille",
  "symbols.symbol_main_switch": "Main switch",
  "symbols.symbol_manifold": "Manifold",
  "symbols.symbol_manual_call_point": "Manual call point",
  "symbols.symbol_meter": "Energy meter",
  "symbols.symbol_mixing_valve": "Three-way mixing valve",
  "symbols.symbol_motion_detector": "Motion detector",
  "symbols.symbol_motor_protection": "Motor protection relay",
  "symbols.symbol_oil_separator": "Oil separator",
  "symbols.symbol_pressure_reducing_valve": "Pressure reducing valve",
  "symbols.symbol_pressure_sensor": "Pressure sensor",
  "symbols.symbol_pump_dhw": "Circulation pump",
  "symbols.symbol_pump_group": "Pump group",
  "symbols.symbol_pump_inline": "Inline pump",
  "symbols.symbol_pump_twin": "Twin pump",
  "symbols.symbol_pump_variable": "Variable-speed pump",
  "symbols.symbol_pv_array": "PV array",
  "symbols.symbol_radiator": "Radiator",
  "symbols.symbol_rcd": "Residual-current device",
  "symbols.symbol_receiver_drier": "Receiver drier",
  "symbols.symbol_reducer": "Reducer",
  "symbols.symbol_room_sensor": "Room sensor",
  "symbols.symbol_safety_valve": "Safety valve",
  "symbols.symbol_shutoff_valve": "Shut-off valve",
  "symbols.symbol_sight_glass": "Sight glass",
  "symbols.symbol_silencer": "Silencer",
  "symbols.symbol_smoke_detector": "Smoke detector",
  "symbols.symbol_solar_controller": "Solar controller",
  "symbols.symbol_solar_station": "Solar station",
  "symbols.symbol_sprinkler_head": "Sprinkler head",
  "symbols.symbol_sprinkler_valve_station": "Wet alarm valve station",
  "symbols.symbol_steam_humidifier": "Steam humidifier",
  "symbols.symbol_sub_distribution_board": "Sub-distribution board",
  "symbols.symbol_suction_accumulator": "Suction accumulator",
  "symbols.symbol_surge_arrester": "Surge arrester",
  "symbols.symbol_switchgear": "Low-voltage switchgear",
  "symbols.symbol_temp_sensor": "Temperature sensor",
  "symbols.symbol_transformer": "Transformer",
  "symbols.symbol_underfloor": "Underfloor heating",
  "symbols.symbol_ups": "UPS",
  "symbols.symbol_vacuum_tube_collector": "Evacuated tube collector",
  "symbols.symbol_valve_2way": "Two-way valve",
  "symbols.symbol_valve_3way": "Three-way valve",
  "symbols.symbol_vav_box": "VAV box",
  "symbols.symbol_wallbox": "Wallbox",
  "symbols.symbol_water_meter": "Water meter",
  "symbols.symbol_y_strainer": "Y-strainer",
  "trends.coverage": "Coverage {percent} %",
  "trends.coverage_gaps": "Coverage {percent} % · {gaps} {gapWord}",
  "trends.gap_one": "gap",
  "trends.gap_other": "gaps",
  "trends.gap_row": "No data from {start} to {end}",
  "trends.instant_column": "Instant",
  "trends.no_data": "No data",
  "trends.report_name": "Report name",
  "trends.report_period": "Period",
  "trends.report_schedule": "Schedule",
  "trends.series_column": "Series {index}",
  "trends.span_day23": "This day has 23 hours — the clock change falls inside it.",
  "trends.span_day25": "This day has 25 hours — the clock change falls inside it.",
  "trends.span_month": "This month has {hours} hours — the clock change falls inside it.",
  "trends.table_label": "Reading table",
  "trends.unreadable": "Unreadable",
});

registerCatalog("en", ENTRIES);
