/**
 * The English catalog.
 *
 * Every user-facing English string the browser renders, in one sorted, flat
 * table of `namespace.name` keys. Values carry named `{placeholder}`
 * templates rather than being functions, because a function cannot be supplied
 * as data — and a locale that cannot be supplied as data is a code edit, which
 * is exactly what I18N-01 says a locale must not be.
 *
 * Sorted, so a diff shows what changed rather than where it was inserted.
 */
import { registerCatalog } from "./catalog-lookup.mjs";

export const ENTRIES = Object.freeze({
  "alarms.acknowledge": "Acknowledge",
  "alarms.alarms_title": "Alarms",
  "alarms.attempts_title": "Delivery attempts",
  "alarms.binding_read_only": "Read-only",
  "alarms.cancel": "Cancel",
  "alarms.comment": "Comment",
  "alarms.confirm": "OK",
  "alarms.delivery_failed": "Delivery failed",
  "alarms.delivery_none": "No notification targets configured; alarms are annunciated here only",
  "alarms.links_title": "Context",
  "alarms.no_alarms": "No active alarms",
  "alarms.preview_ambiguous": "occurs twice on",
  "alarms.preview_ambiguous_tail": "this entry runs once, at",
  "alarms.preview_nonexistent": "does not exist on",
  "alarms.preview_nonexistent_tail": "this entry will not run",
  "alarms.preview_normal": "runs at",
  "alarms.priority_critical": "Critical",
  "alarms.priority_info": "Information",
  "alarms.priority_warning": "Warning",
  "alarms.schedule_kind_instant": "Runs at a time",
  "alarms.schedule_kind_interval": "Operating period",
  "alarms.schedule_preview": "Effective times",
  "alarms.schedule_title": "Schedules",
  "alarms.setting_default": "default",
  "alarms.settings_title": "Alarm settings",
  "alarms.shelve": "Shelve",
  "alarms.shelve_minutes": "Suppress for how many minutes?",
  "alarms.shelve_too_long": "Longer than this site allows",
  "alarms.state_acknowledged": "acknowledged",
  "alarms.state_active": "active",
  "alarms.state_indeterminate": "state unknown",
  "alarms.state_returned": "returned",
  "alarms.state_suppressed": "suppressed",
  "alarms.suppressed_acknowledged": "acknowledged",
  "alarms.suppressed_by": "by",
  "alarms.suppressed_maintenance": "in maintenance",
  "alarms.suppressed_shelved": "shelved",
  "alarms.suppressed_until": "until",
  "assets.attachment_limits": "At most {count} attachments, each up to {megabytes} MB.",
  "assets.column_declared_in": "Declared in",
  "assets.column_diagnosis": "Diagnosis",
  "assets.column_evidence": "Evidence",
  "assets.column_note": "Note",
  "assets.column_provenance": "Provenance",
  "assets.column_reference": "Reference",
  "assets.column_slot": "Slot",
  "assets.column_tick": "Tick",
  "assets.column_value": "Value",
  "assets.diagnosis_duplicate_binding": "duplicate binding",
  "assets.diagnosis_missing": "missing",
  "assets.diagnosis_present": "present",
  "assets.diagnosis_registered_not_loaded": "registered but not loaded",
  "assets.diagnosis_service_missing": "service missing",
  "assets.diagnosis_stale": "stale",
  "assets.diagnosis_unregistered": "no registry entry",
  "assets.diagnosis_wrong_device_class": "wrong device class",
  "assets.diagnosis_wrong_unit": "wrong unit",
  "assets.field_asset": "Asset",
  "assets.field_note": "Note",
  "assets.field_reason": "Reason",
  "assets.field_title": "Task",
  "assets.measured": "measured",
  "assets.no_entries": "No entries.",
  "assets.read_only": "This view changes nothing. Every remediation is a link, not an action.",
  "assets.refused_simulating": "Not performed: a simulation is running.",
  "assets.refused_unknown": "Not performed: the simulation state could not be determined. Please try again.",
  "assets.session_active": "Simulation active — started by {who}, ends {until}. The plant is not being operated.",
  "assets.session_expired": "The simulation has expired. The plant is being operated again.",
  "assets.simulated": "simulated",
  "assets.simulated_shape": "◈",
  "catalog.catalog_title": "Symbol catalog",
  "catalog.direction_bidirectional": "Both ways",
  "catalog.direction_in": "Inlet",
  "catalog.direction_out": "Outlet",
  "catalog.filter_all": "All",
  "catalog.filter_category": "Category",
  "catalog.filter_domain": "Domain",
  "catalog.filter_style": "Style",
  "catalog.filter_text": "Search",
  "catalog.kind_power": "Power",
  "catalog.kind_process": "Process",
  "catalog.kind_signal": "Signal",
  "catalog.multiplicity_full": "At its limit",
  "catalog.multiplicity_many": "Many connections",
  "catalog.multiplicity_one": "One connection",
  "catalog.no_matches": "No symbol matches these filters",
  "catalog.port_direction": "Direction",
  "catalog.port_kind": "Kind",
  "catalog.port_medium": "Medium",
  "catalog.port_multiplicity": "Connections",
  "catalog.port_side": "Side",
  "catalog.published_variants": "published variants",
  "catalog.refusal_direction_conflict": "The directions conflict: both ports point the same way.",
  "catalog.refusal_duplicate_connection": "These two ports are already connected.",
  "catalog.refusal_kind_mismatch": "The kinds differ: a process port cannot join a signal or power port.",
  "catalog.refusal_medium_mismatch": "The media differ: these two ports carry different things.",
  "catalog.refusal_multiplicity_exceeded": "That port already has the one connection it admits.",
  "catalog.refusal_self_connection": "A port cannot be connected to itself.",
  "catalog.refusal_title": "This connection is not possible",
  "catalog.refusal_unknown": "The connection was refused.",
  "designer.add": "Add object",
  "designer.align": "Align",
  "designer.canvas_label": "Designer canvas",
  "designer.confirm_delete": "Delete the selected objects?",
  "designer.confirm_remove_pack": "Remove this extension pack?",
  "designer.conflict": "Conflict",
  "designer.connect": "Connect ports",
  "designer.connect_choose_source": "Choose the source port",
  "designer.connect_choose_target": "Choose the target port",
  "designer.connect_refused": "Connection refused",
  "designer.contributes": "Contributes",
  "designer.delete": "Delete",
  "designer.disconnect": "Disconnect",
  "designer.distribute": "Distribute",
  "designer.extend_selection": "Extend selection",
  "designer.extensions": "Installed extensions",
  "designer.group": "Group",
  "designer.instantiate_master": "Place master instance",
  "designer.keyboard_help": "Keyboard",
  "designer.layer_hidden": "Hidden",
  "designer.layer_locked": "Locked",
  "designer.layer_unlocked": "Unlocked",
  "designer.layer_visible": "Visible",
  "designer.layers": "Layers",
  "designer.minimap_label": "Diagram overview",
  "designer.no_extensions": "No extension packs are installed",
  "designer.nothing_selected": "Nothing selected",
  "designer.nudge_coarse": "Nudge, coarse",
  "designer.nudge_fine": "Nudge",
  "designer.objects": "objects",
  "designer.ready": "Ready",
  "designer.redo": "Redo",
  "designer.reorder": "Bring forward",
  "designer.resize": "Resize",
  "designer.select": "Select",
  "designer.supports": "Supports project schema",
  "designer.undo": "Undo",
  "designer.undo_depth": "Undo steps kept",
  "designer.ungroup": "Ungroup",
  "designer.viewport": "Current view",
  "equipment.command_failed": "Command failed",
  "equipment.command_pending": "Command pending",
  "equipment.communication_error": "Communication error",
  "equipment.fault": "Fault",
  "equipment.interlock": "Interlocked",
  "equipment.invalid": "Invalid value",
  "equipment.local": "Local control",
  "equipment.locked": "Locked",
  "equipment.maintenance": "Maintenance",
  "equipment.manual": "Manual",
  "equipment.off": "Off",
  "equipment.running": "Running",
  "equipment.stale": "Value not current",
  "equipment.standby": "Standby",
  "equipment.unknown": "Unknown",
  "equipment.warning": "Warning",
  "operations.affordance_audit": "Open trusted audit",
  "operations.affordance_cancel": "Cancel",
  "operations.affordance_dismiss": "Dismiss",
  "operations.affordance_state": "Show current state",
  "operations.history_unavailable": "Trends are not available yet",
  "operations.last_updated": "Last updated",
  "operations.no_alarms": "No alarms",
  "operations.no_controls_available": "No controls available to you",
  "operations.no_values_declared": "No values declared",
  "operations.outcome_accepted": "Accepted — awaiting dispatch",
  "operations.outcome_cancelled": "Cancelled — not sent",
  "operations.outcome_confirmed": "Confirmed",
  "operations.outcome_denied": "Not permitted",
  "operations.outcome_dispatched": "Sent — awaiting confirmation",
  "operations.outcome_failed_after_dispatch": "Failed after dispatch — effect unknown",
  "operations.outcome_failed_before_dispatch": "Failed — not sent",
  "operations.outcome_result_unknown": "Effect unknown",
  "operations.outcome_timed_out": "No confirmation — effect unknown",
  "operations.status_live": "Live",
  "operations.status_resyncing": "Reloading",
  "operations.status_stale": "Not live — showing last known values",
  "operations.status_unavailable": "Unavailable",
  "operations.view_not_available": "This view is not available.",
  "period.change": "Consumption",
  "period.circular_mean_required": "This quantity is a direction — an arithmetic mean would be wrong.",
  "period.custom": "Custom range",
  "period.day": "Day",
  "period.entities_exceed_limit": "The query names more entities than the site permits.",
  "period.incompatible_unit": "The unit and the price do not match — they cannot be combined.",
  "period.max": "Maximum",
  "period.mean": "Mean",
  "period.min": "Minimum",
  "period.month": "Month",
  "period.none": "Every sample",
  "period.outside_statistic_coverage": "This period lies before the first recorded value.",
  "period.raw": "from raw values",
  "period.state": "Meter reading",
  "period.statistics": "from long-term statistics",
  "period.unavailable": "unavailable",
  "period.undeclared_meter_model": "This meter does not declare whether it counts or measures.",
  "period.unknown_aggregate": "That aggregate is not known.",
  "period.unknown_period": "That period is not known.",
  "period.unknown_source": "That source is not known.",
  "period.week": "Week",
  "period.window_exceeds_limit": "The window is longer than raw values permit.",
  "period.year": "Year",
  "replay.before_first_sample": "Before the first recorded value",
  "replay.no_recorded_history": "No history recorded",
  "replay.outside_loaded_window": "Outside the loaded window",
  "safety.access_denied": "The access change was refused. Nothing changed.",
  "safety.access_empty": "No member holds a role on this project yet.",
  "safety.access_heading": "Project access",
  "safety.access_loading": "Loading project access",
  "safety.access_revision": "Access revision",
  "safety.access_saved": "Access change applied",
  "safety.acquire_lease": "Acquire editing lease",
  "safety.action_column": "Action",
  "safety.add_member": "Add member",
  "safety.announcements_authority_current": "Server authority refreshed.",
  "safety.announcements_evidence_page_failed": "The next evidence page could not be loaded.",
  "safety.announcements_lease_acquired": "Editing lease acquired by this session.",
  "safety.announcements_lease_held": "Another session is editing.",
  "safety.announcements_lease_released": "Editing lease released.",
  "safety.announcements_lease_renewed": "Editing lease renewed.",
  "safety.apply_access_change": "Apply access change",
  "safety.apply_failure": "Project changes were not applied. Nothing was changed. Review the diagnostic and run a fresh dry run.",
  "safety.apply_selected": "Apply selected changes",
  "safety.apply_success": "Project changes applied",
  "safety.apply_success_body": "Revision {revision} was validated and verified after applying {count} changes. Verified backup {backup_id} remains available.",
  "safety.applying": "Applying {count} project changes",
  "safety.artifact_equality": "Artifact equality",
  "safety.asset_metadata": "Opaque asset metadata",
  "safety.assigned": "Assigned",
  "safety.assignment_column": "Assignment",
  "safety.audit_actor": "Actor",
  "safety.audit_at": "Server time",
  "safety.audit_correlation": "Correlation ID",
  "safety.audit_event": "Event",
  "safety.audit_result": "Result",
  "safety.authority_bar": "Authority state",
  "safety.back_to_overview": "Back to overview",
  "safety.bundle_empty": "No bundle inspected. Project asset metadata is listed without rendering asset content.",
  "safety.bundle_safety": "Bundle safety",
  "safety.byte_identical": "Byte-identical",
  "safety.cancel_access_change": "Cancel access change",
  "safety.cancel_apply": "Cancel project changes",
  "safety.cancel_discard": "Keep my changes",
  "safety.candidate_heading": "Unsaved candidate",
  "safety.candidate_states_applied": "Applied",
  "safety.candidate_states_dirty": "Unsaved changes in this session",
  "safety.candidate_states_none": "No unsaved changes",
  "safety.candidate_states_preserved": "Unsaved changes kept in memory",
  "safety.capabilities_column": "Effective capabilities",
  "safety.capability_codes": "Show capability codes",
  "safety.categories_add": "Added",
  "safety.categories_binding": "Binding",
  "safety.categories_config": "Configuration",
  "safety.categories_move": "Moved",
  "safety.categories_remove": "Removed",
  "safety.check_lease": "Check lease availability",
  "safety.checksum": "SHA-256",
  "safety.choose_user": "Choose an eligible user",
  "safety.client_telemetry": "Client telemetry (untrusted)",
  "safety.close": "Close Project safety",
  "safety.collaboration": "Collaboration",
  "safety.companion": "Companion",
  "safety.companion_states_current": "Authority current",
  "safety.companion_states_incompatible": "Policy version unsupported",
  "safety.companion_states_refreshing": "Refreshing authority",
  "safety.companion_states_stale": "Authority stale",
  "safety.companion_states_unavailable": "Companion unavailable",
  "safety.confirm_access_body": "Change {member} to {role} at access revision {revision}? The change is applied atomically and recorded in the trusted audit.",
  "safety.confirm_access_heading": "Confirm access change",
  "safety.confirm_apply_body": "Apply {count} validated changes to “{project}” at revision {revision}? A verified backup will be created first. This changes project data only and sends no plant command.",
  "safety.confirm_apply_heading": "Confirm project changes",
  "safety.confirm_remove_body": "Remove all access for {member} at access revision {revision}? They keep no role on this project.",
  "safety.conflict_body": "Revision {base} is no longer current; revision {current} is active. Your candidate is kept in memory. Nothing was overwritten.",
  "safety.conflict_choices_discard": "Discard my changes",
  "safety.conflict_choices_merge_preview": "Preview a merge",
  "safety.conflict_choices_refresh": "Refresh from the server",
  "safety.conflict_choices_retry_with_fresh_lease": "Retry with a fresh lease",
  "safety.conflict_heading": "Save blocked — a newer revision exists",
  "safety.connected": "Connected",
  "safety.control_cancel": "Cancel control",
  "safety.control_confirm_body": "Run “{label}”? The Companion resolves the effect from the current project head; this card sends only the control name and the declared input.",
  "safety.control_confirm_heading": "Confirm configured control",
  "safety.control_correlation": "Correlation ID",
  "safety.control_effect": "Resolved effect",
  "safety.control_heading": "Configured control",
  "safety.control_no_retry": "This card never repeats a control by itself. Decide again if the plant must move.",
  "safety.control_policy": "Control policy",
  "safety.control_preview": "Preview control",
  "safety.control_run": "Run control",
  "safety.control_states_accepted": "Accepted and recorded. Not yet dispatched.",
  "safety.control_states_cancelled_before_dispatch": "Cancelled. Nothing was sent.",
  "safety.control_states_denied": "Denied.",
  "safety.control_states_dispatched": "Dispatched to Home Assistant. Not yet confirmed.",
  "safety.control_states_failed_after_dispatch": "Failed after dispatch. The effect is unknown — check the current state and the trusted audit.",
  "safety.control_states_failed_before_dispatch": "Failed before dispatch. Nothing was sent.",
  "safety.control_states_readback_confirmed": "Confirmed by readback.",
  "safety.control_states_result_unknown": "The result is unknown — check the current state and the trusted audit before acting again.",
  "safety.control_states_timed_out": "Timed out. The effect is unknown — check the current state and the trusted audit.",
  "safety.control_target": "Target",
  "safety.controls_visible": "{count} controls visible to you",
  "safety.current_revision": "Revision",
  "safety.discard_body": "Discard the unsaved changes in this session? They cannot be recovered afterwards.",
  "safety.discard_heading": "Discard unsaved changes",
  "safety.dry_run": "Run dry run",
  "safety.dry_run_fresh": "Run fresh dry run",
  "safety.editing": "Editing",
  "safety.eligible_user": "Eligible user",
  "safety.error_codes_authority_stale": "Server authority is stale. Refresh and try again.",
  "safety.error_codes_capability_denied": "Your role does not permit this action.",
  "safety.error_codes_effect_unknown": "The result is unknown. Check the trusted audit before retrying.",
  "safety.error_codes_feature_unavailable": "This feature is not available in this version.",
  "safety.error_codes_invalid_input": "The request was rejected as invalid. Nothing changed.",
  "safety.error_codes_lease_expired": "The editing lease expired.",
  "safety.error_codes_lease_held": "Another session is editing.",
  "safety.error_codes_lease_required": "An editing lease is required.",
  "safety.error_codes_not_found_or_denied": "This project is not available to you.",
  "safety.error_codes_not_loaded": "The Companion is not loaded.",
  "safety.error_codes_rate_limited": "Too many requests. Wait and try again.",
  "safety.error_codes_revision_conflict": "A newer revision exists. Your candidate is kept.",
  "safety.errors": "Validation issues",
  "safety.exact_card_version": "Exact card version",
  "safety.expected_revision": "Expected",
  "safety.export_telemetry": "Export client telemetry",
  "safety.export_trusted": "Export trusted audit",
  "safety.ignored_noise": "Ignored ordering noise",
  "safety.impact": "Impact",
  "safety.inspect_bundle": "Inspect .gltproject bundle",
  "safety.last_refresh": "Last refresh",
  "safety.lease_acquiring": "Requesting exclusive editing lease",
  "safety.lease_expires_in": "Expires in {seconds}s",
  "safety.lease_heading": "Engineering lease",
  "safety.lease_renew_due": "Renewal is due. Renew before the lease expires.",
  "safety.lease_states_available": "Lease available",
  "safety.lease_states_expired": "Lease expired",
  "safety.lease_states_held_other": "Another session is editing",
  "safety.lease_states_held_self": "This session",
  "safety.lease_states_lost": "Lease lost",
  "safety.lease_states_read_only": "Read-only",
  "safety.lease_states_renewing": "Renewing",
  "safety.load_next": "Load next 50 events",
  "safety.manage_access": "Manage project access",
  "safety.media_type": "Media type",
  "safety.member_column": "Member",
  "safety.merge_states_applied": "Merge applied",
  "safety.merge_states_blocked": "The same paths changed on both sides. Choose a different recovery.",
  "safety.merge_states_failed": "The merge preview failed. Your candidate is unchanged.",
  "safety.merge_states_idle": "No merge preview requested.",
  "safety.merge_states_ready": "Merge preview ready. Select the changes to keep.",
  "safety.merge_states_requested": "Requesting merge preview",
  "safety.mode_local": "Local-only project",
  "safety.mode_shared": "Shared project",
  "safety.my_access": "My access",
  "safety.my_role": "My role",
  "safety.never": "Never",
  "safety.no_capabilities": "No capabilities on this project.",
  "safety.no_evidence": "Release evidence is incomplete. Missing or stale gates are listed below.",
  "safety.not_evidence": "Not security or control evidence",
  "safety.not_run": "Not run",
  "safety.overview": "Project safety overview",
  "safety.path": "Path",
  "safety.policy_version": "Policy version",
  "safety.preview_failed": "Migration preview failed. The original project is unchanged. Run a fresh dry run after reviewing the diagnostic.",
  "safety.preview_ready": "Migration preview ready",
  "safety.project": "Project",
  "safety.raw_contract": "Raw contract",
  "safety.read_only": "Read-only",
  "safety.read_only_reasons_authority_absent": "No server authority yet. Shared editing stays read-only until the Companion answers.",
  "safety.read_only_reasons_authority_incompatible": "The Companion uses a policy version this card does not support.",
  "safety.read_only_reasons_authority_loading": "Refreshing server authority. Shared editing is read-only until it returns.",
  "safety.read_only_reasons_authority_rejected": "The Companion refused the authority refresh. Shared editing is read-only.",
  "safety.read_only_reasons_authority_sequence_gap": "An authority update was missed. Refresh before editing.",
  "safety.read_only_reasons_authority_stale": "Server authority is stale. Refresh before editing.",
  "safety.read_only_reasons_companion_disconnected": "The Companion is unavailable. Shared editing is read-only.",
  "safety.read_only_reasons_lease_expired": "The editing lease expired. Your unsaved candidate is kept.",
  "safety.read_only_reasons_lease_lost": "The editing lease was lost. Your unsaved candidate is kept.",
  "safety.read_only_reasons_lease_required": "Acquire the editing lease to make changes.",
  "safety.read_only_reasons_role_missing": "You have no role on this project.",
  "safety.read_only_reasons_role_revoked": "Your role for this project changed. Shared editing is read-only.",
  "safety.release_evidence": "Release evidence",
  "safety.release_lease": "Release editing lease",
  "safety.remove_access": "Remove access",
  "safety.renew_lease": "Renew editing lease",
  "safety.required_dependency": "Required dependency",
  "safety.restore": "Restore verified backup",
  "safety.restore_awaiting": "Enter “{project}” to enable Restore verified backup.",
  "safety.restore_body": "Restore verified backup {backup_id} for “{project}”? The current revision {revision} will be replaced. A new evidence receipt will be created. This changes project data only and sends no plant command.",
  "safety.restore_label": "Enter the project name to confirm",
  "safety.restore_mismatch": "The project name does not match. The project remains unchanged.",
  "safety.restore_ready": "Project name confirmed. Review the revision and backup before continuing.",
  "safety.revision": "Revision",
  "safety.revision_conflict": "Revision {expected} is no longer current; revision {actual} is active. Reload and compare again.",
  "safety.revision_triplet": "Base {base} · Current {current} · Candidate {candidate}",
  "safety.role_column": "Role",
  "safety.role_matrix": "Role capability matrix",
  "safety.role_matrix_unavailable": "The Companion did not return a capability matrix for this role.",
  "safety.role_names_admin": "Admin",
  "safety.role_names_engineer": "Engineer",
  "safety.role_names_none": "No assignment",
  "safety.role_names_operator": "Operator",
  "safety.role_names_viewer": "Viewer",
  "safety.rollback_failure": "Backup restore verification failed. Both snapshots were retained. Download the rollback diagnostic and request administrator recovery.",
  "safety.rollback_running": "Restoring verified backup",
  "safety.rollback_success": "Verified backup restored",
  "safety.rollback_success_body": "Project revision {revision} matches verified backup {backup_id}. A rollback evidence receipt was created.",
  "safety.rows_stale": "The next page could not be loaded. The events shown are no longer current.",
  "safety.schema": "Schema",
  "safety.scope": "Project data only — no Home Assistant service or plant command is executed.",
  "safety.server_authored": "Server-authored",
  "safety.server_normalization": "Server normalization active",
  "safety.shared_authority": "Shared authority",
  "safety.size": "Size",
  "safety.standalone": "Companion unavailable — shared project operations are read-only.",
  "safety.tabs_0": "Overview",
  "safety.tabs_1": "Validate",
  "safety.tabs_2": "Migrate & compare",
  "safety.tabs_3": "Bundles",
  "safety.tabs_4": "Evidence",
  "safety.telemetry_category": "Category",
  "safety.telemetry_empty": "No client telemetry has been recorded in this session.",
  "safety.telemetry_payload": "Payload summary",
  "safety.telemetry_received": "Received",
  "safety.title": "Project safety",
  "safety.trusted_audit": "Trusted audit",
  "safety.trusted_empty": "No trusted audit event is visible to you yet.",
  "safety.unchanged": "Original project unchanged",
  "safety.validate": "Validate project",
  "safety.validation_failed": "Project validation failed",
  "safety.validation_idle": "Choose Validate project to inspect the raw project without changing it.",
  "safety.validation_invalid": "The project is invalid. Review the listed paths; the original remains unchanged.",
  "safety.validation_running": "Validating raw project",
  "safety.validation_success": "Project validation complete",
  "safety.validation_valid": "No validation issues found. The raw project matches schema {version}.",
  "safety.workflow_0": "Inspect",
  "safety.workflow_1": "Preview",
  "safety.workflow_2": "Backup",
  "safety.workflow_3": "Apply",
  "safety.workflow_4": "Verify",
  "sites.age": "read {seconds} s ago",
  "sites.completeness": "{answered} of {total} sites answered",
  "sites.effect_unknown": "Effect unknown — the command may have run. Check the plant state before sending anything again.",
  "sites.missing_sites": "Missing sites:",
  "sites.no_value": "no reading",
  "sites.shape_circuit_open": "✕",
  "sites.shape_healthy": "●",
  "sites.shape_slow": "◐",
  "sites.shape_unreachable": "○",
  "sites.site_circuit_open": "suspended after repeated failures",
  "sites.site_healthy": "reachable",
  "sites.site_slow": "slow",
  "sites.site_unreachable": "unreachable",
  "sites.unverified_tls": "unverified: this site's certificate is not checked",
  "symbols.label": "Heating",
  "symbols.label_brandschutz": "Fire safety",
  "symbols.label_elektro": "Electrical",
  "symbols.label_energie": "Energy",
  "symbols.label_hydraulik": "Hydraulics",
  "symbols.label_k_lte": "Refrigeration",
  "symbols.label_rlt": "Air handling",
  "symbols.label_sensorik": "Instrumentation",
  "trends.coverage": "Coverage {percent} %",
  "trends.coverage_gaps": "Coverage {percent} % · {gaps} {gapWord}",
  "trends.gap_one": "gap",
  "trends.gap_other": "gaps",
  "trends.gap_row": "No data from {start} to {end}",
  "trends.instant_column": "Instant",
  "trends.no_data": "No data",
  "trends.report_name": "Report name",
  "trends.report_period": "Period",
  "trends.report_schedule": "Schedule",
  "trends.series_column": "Series {index}",
  "trends.span_day23": "This day has 23 hours — the clock change falls inside it.",
  "trends.span_day25": "This day has 25 hours — the clock change falls inside it.",
  "trends.span_month": "This month has {hours} hours — the clock change falls inside it.",
  "trends.table_label": "Reading table",
  "trends.unreadable": "Unreadable",
});

registerCatalog("en", ENTRIES);
