/**
 * The German catalog.
 *
 * Every user-facing German string the browser renders, in one sorted, flat
 * table of `namespace.name` keys. Values carry named `{placeholder}`
 * templates rather than being functions, because a function cannot be supplied
 * as data — and a locale that cannot be supplied as data is a code edit, which
 * is exactly what I18N-01 says a locale must not be.
 *
 * Sorted, so a diff shows what changed rather than where it was inserted.
 */
import { registerCatalog } from "./catalog-lookup.mjs";

export const ENTRIES = Object.freeze({
  "alarms.acknowledge": "Quittieren",
  "alarms.alarms_title": "Alarme",
  "alarms.attempts_title": "Zustellversuche",
  "alarms.binding_read_only": "Nur lesbar",
  "alarms.cancel": "Abbrechen",
  "alarms.comment": "Kommentar",
  "alarms.confirm": "OK",
  "alarms.delivery_failed": "Zustellung fehlgeschlagen",
  "alarms.delivery_none": "Keine Benachrichtigungsziele konfiguriert; Alarme werden nur hier angezeigt",
  "alarms.links_title": "Kontext",
  "alarms.no_alarms": "Keine aktiven Alarme",
  "alarms.preview_ambiguous": "kommt zweimal vor am",
  "alarms.preview_ambiguous_tail": "dieser Eintrag läuft einmal, um",
  "alarms.preview_nonexistent": "gibt es nicht am",
  "alarms.preview_nonexistent_tail": "dieser Eintrag läuft nicht",
  "alarms.preview_normal": "läuft um",
  "alarms.priority_critical": "Störung",
  "alarms.priority_info": "Hinweis",
  "alarms.priority_warning": "Warnung",
  "alarms.schedule_kind_instant": "Läuft zu einer Zeit",
  "alarms.schedule_kind_interval": "Betriebszeit",
  "alarms.schedule_preview": "Wirksame Zeiten",
  "alarms.schedule_title": "Zeitprogramme",
  "alarms.setting_default": "Vorgabe",
  "alarms.settings_title": "Alarmeinstellungen",
  "alarms.shelve": "Unterdrücken",
  "alarms.shelve_minutes": "Für wie viele Minuten unterdrücken?",
  "alarms.shelve_too_long": "Länger als dieser Standort erlaubt",
  "alarms.state_acknowledged": "quittiert",
  "alarms.state_active": "aktiv",
  "alarms.state_indeterminate": "Zustand unbekannt",
  "alarms.state_returned": "zurückgestellt",
  "alarms.state_suppressed": "unterdrückt",
  "alarms.suppressed_acknowledged": "quittiert",
  "alarms.suppressed_by": "von",
  "alarms.suppressed_maintenance": "in Wartung",
  "alarms.suppressed_shelved": "geschelft",
  "alarms.suppressed_until": "bis",
  "assets.attachment_limits": "Höchstens {count} Anhänge, je bis {megabytes} MB.",
  "assets.diagnosis_duplicate_binding": "doppelte Zuordnung",
  "assets.diagnosis_missing": "fehlt",
  "assets.diagnosis_present": "vorhanden",
  "assets.diagnosis_registered_not_loaded": "registriert, aber nicht geladen",
  "assets.diagnosis_service_missing": "Dienst fehlt",
  "assets.diagnosis_stale": "veraltet",
  "assets.diagnosis_unregistered": "ohne Registry-Eintrag",
  "assets.diagnosis_wrong_device_class": "falsche Geräteklasse",
  "assets.diagnosis_wrong_unit": "falsche Einheit",
  "assets.measured": "gemessen",
  "assets.no_entries": "Keine Einträge.",
  "assets.read_only": "Diese Ansicht ändert nichts. Alle Hinweise sind Verweise, keine Aktionen.",
  "assets.refused_simulating": "Nicht ausgeführt: eine Simulation läuft.",
  "assets.refused_unknown": "Nicht ausgeführt: der Simulationszustand war nicht feststellbar. Bitte erneut versuchen.",
  "assets.session_active": "Simulation aktiv — gestartet von {who}, endet {until}. Die Anlage wird nicht bedient.",
  "assets.session_expired": "Die Simulation ist abgelaufen. Die Anlage wird wieder bedient.",
  "assets.simulated": "simuliert",
  "assets.simulated_shape": "◈",
  "catalog.catalog_title": "Symbolkatalog",
  "catalog.direction_bidirectional": "Beide Richtungen",
  "catalog.direction_in": "Eingang",
  "catalog.direction_out": "Ausgang",
  "catalog.filter_all": "Alle",
  "catalog.filter_category": "Kategorie",
  "catalog.filter_domain": "Gewerk",
  "catalog.filter_style": "Stil",
  "catalog.filter_text": "Suche",
  "catalog.kind_power": "Energie",
  "catalog.kind_process": "Prozess",
  "catalog.kind_signal": "Signal",
  "catalog.multiplicity_full": "Bereits belegt",
  "catalog.multiplicity_many": "Mehrere Verbindungen",
  "catalog.multiplicity_one": "Eine Verbindung",
  "catalog.no_matches": "Kein Symbol passt zu diesen Filtern",
  "catalog.port_direction": "Richtung",
  "catalog.port_kind": "Art",
  "catalog.port_medium": "Medium",
  "catalog.port_multiplicity": "Verbindungen",
  "catalog.port_side": "Seite",
  "catalog.published_variants": "veröffentlichte Varianten",
  "catalog.refusal_direction_conflict": "Die Richtungen widersprechen sich: beide Ports zeigen gleich.",
  "catalog.refusal_duplicate_connection": "Diese beiden Ports sind bereits verbunden.",
  "catalog.refusal_kind_mismatch": "Die Arten unterscheiden sich: Prozess passt nicht zu Signal oder Energie.",
  "catalog.refusal_medium_mismatch": "Die Medien unterscheiden sich: die Ports führen Verschiedenes.",
  "catalog.refusal_multiplicity_exceeded": "Dieser Port hat die eine Verbindung bereits, die er zulässt.",
  "catalog.refusal_self_connection": "Ein Port kann nicht mit sich selbst verbunden werden.",
  "catalog.refusal_title": "Diese Verbindung ist nicht möglich",
  "catalog.refusal_unknown": "Die Verbindung wurde abgelehnt.",
  "designer.add": "Objekt hinzufügen",
  "designer.align": "Ausrichten",
  "designer.canvas_label": "Konstruktionsfläche",
  "designer.confirm_delete": "Ausgewählte Objekte löschen?",
  "designer.confirm_remove_pack": "Dieses Erweiterungspaket entfernen?",
  "designer.conflict": "Konflikt",
  "designer.connect": "Ports verbinden",
  "designer.connect_choose_source": "Quell-Port wählen",
  "designer.connect_choose_target": "Ziel-Port wählen",
  "designer.connect_refused": "Verbindung abgelehnt",
  "designer.contributes": "Enthält",
  "designer.delete": "Löschen",
  "designer.disconnect": "Verbindung trennen",
  "designer.distribute": "Verteilen",
  "designer.extend_selection": "Auswahl erweitern",
  "designer.extensions": "Installierte Erweiterungen",
  "designer.group": "Gruppieren",
  "designer.instantiate_master": "Master-Instanz setzen",
  "designer.keyboard_help": "Tastatur",
  "designer.layer_hidden": "Ausgeblendet",
  "designer.layer_locked": "Gesperrt",
  "designer.layer_unlocked": "Entsperrt",
  "designer.layer_visible": "Sichtbar",
  "designer.layers": "Ebenen",
  "designer.minimap_label": "Übersicht",
  "designer.no_extensions": "Es sind keine Erweiterungspakete installiert",
  "designer.nothing_selected": "Nichts ausgewählt",
  "designer.nudge_coarse": "Verschieben, grob",
  "designer.nudge_fine": "Verschieben",
  "designer.objects": "Objekte",
  "designer.ready": "Bereit",
  "designer.redo": "Wiederherstellen",
  "designer.reorder": "Nach vorn holen",
  "designer.resize": "Größe ändern",
  "designer.select": "Auswählen",
  "designer.supports": "Unterstützt Projektschema",
  "designer.undo": "Rückgängig",
  "designer.undo_depth": "Aufbewahrte Schritte",
  "designer.ungroup": "Gruppierung aufheben",
  "designer.viewport": "Aktueller Ausschnitt",
  "operations.affordance_audit": "Vertrauenswürdiges Protokoll öffnen",
  "operations.affordance_cancel": "Abbrechen",
  "operations.affordance_dismiss": "Schließen",
  "operations.affordance_state": "Aktuellen Zustand zeigen",
  "operations.history_unavailable": "Trends sind noch nicht verfügbar",
  "operations.last_updated": "Zuletzt aktualisiert",
  "operations.no_alarms": "Keine Alarme",
  "operations.no_controls_available": "Keine Bedienung für Sie verfügbar",
  "operations.no_values_declared": "Keine Werte deklariert",
  "operations.outcome_accepted": "Angenommen — wartet auf Absendung",
  "operations.outcome_cancelled": "Abgebrochen — nicht gesendet",
  "operations.outcome_confirmed": "Bestätigt",
  "operations.outcome_denied": "Nicht berechtigt",
  "operations.outcome_dispatched": "Gesendet — wartet auf Bestätigung",
  "operations.outcome_failed_after_dispatch": "Nach Absendung fehlgeschlagen — Wirkung unbekannt",
  "operations.outcome_failed_before_dispatch": "Fehlgeschlagen — nicht gesendet",
  "operations.outcome_result_unknown": "Wirkung unbekannt",
  "operations.outcome_timed_out": "Keine Bestätigung — Wirkung unbekannt",
  "operations.status_live": "Live",
  "operations.status_resyncing": "Wird neu geladen",
  "operations.status_stale": "Nicht live — letzte bekannte Werte",
  "operations.status_unavailable": "Nicht verfügbar",
  "operations.view_not_available": "Diese Ansicht ist nicht verfügbar.",
  "safety.access_denied": "Die Zugriffsänderung wurde abgelehnt. Es wurde nichts geändert.",
  "safety.access_empty": "Bisher hat kein Mitglied eine Rolle in diesem Projekt.",
  "safety.access_heading": "Projektzugriff",
  "safety.access_loading": "Projektzugriff wird geladen",
  "safety.access_revision": "Zugriffsrevision",
  "safety.access_saved": "Zugriffsänderung übernommen",
  "safety.acquire_lease": "Bearbeitungslease anfordern",
  "safety.action_column": "Aktion",
  "safety.add_member": "Mitglied hinzufügen",
  "safety.announcements_authority_current": "Serverautorität aktualisiert.",
  "safety.announcements_evidence_page_failed": "Die nächste Nachweisseite konnte nicht geladen werden.",
  "safety.announcements_lease_acquired": "Bearbeitungslease von dieser Sitzung übernommen.",
  "safety.announcements_lease_held": "Eine andere Sitzung bearbeitet gerade.",
  "safety.announcements_lease_released": "Bearbeitungslease freigegeben.",
  "safety.announcements_lease_renewed": "Bearbeitungslease verlängert.",
  "safety.apply_access_change": "Zugriffsänderung übernehmen",
  "safety.apply_failure": "Projektänderungen wurden nicht übernommen. Es wurde nichts geändert. Prüfen Sie die Diagnose und starten Sie einen neuen Probelauf.",
  "safety.apply_selected": "Ausgewählte Änderungen übernehmen",
  "safety.apply_success": "Projektänderungen übernommen",
  "safety.apply_success_body": "Revision {revision} wurde nach dem Übernehmen von {count} Änderungen validiert und verifiziert. Das verifizierte Backup {backup_id} bleibt verfügbar.",
  "safety.applying": "{count} Projektänderungen werden übernommen",
  "safety.artifact_equality": "Artefaktgleichheit",
  "safety.asset_metadata": "Undurchsichtige Asset-Metadaten",
  "safety.assigned": "Zugewiesen",
  "safety.assignment_column": "Zuweisung",
  "safety.audit_actor": "Akteur",
  "safety.audit_at": "Serverzeit",
  "safety.audit_correlation": "Korrelations-ID",
  "safety.audit_event": "Ereignis",
  "safety.audit_result": "Ergebnis",
  "safety.authority_bar": "Autoritätsstatus",
  "safety.back_to_overview": "Zurück zur Übersicht",
  "safety.bundle_empty": "Kein Paket geprüft. Projekt-Asset-Metadaten werden ohne Darstellung der Inhalte aufgelistet.",
  "safety.bundle_safety": "Paketsicherheit",
  "safety.byte_identical": "Byte-identisch",
  "safety.cancel_access_change": "Zugriffsänderung abbrechen",
  "safety.cancel_apply": "Projektänderungen abbrechen",
  "safety.cancel_discard": "Änderungen behalten",
  "safety.candidate_heading": "Ungespeicherter Entwurf",
  "safety.candidate_states_applied": "Übernommen",
  "safety.candidate_states_dirty": "Ungespeicherte Änderungen in dieser Sitzung",
  "safety.candidate_states_none": "Keine ungespeicherten Änderungen",
  "safety.candidate_states_preserved": "Ungespeicherte Änderungen im Speicher erhalten",
  "safety.capabilities_column": "Effektive Berechtigungen",
  "safety.capability_codes": "Berechtigungscodes anzeigen",
  "safety.categories_add": "Hinzugefügt",
  "safety.categories_binding": "Bindung",
  "safety.categories_config": "Konfiguration",
  "safety.categories_move": "Verschoben",
  "safety.categories_remove": "Entfernt",
  "safety.check_lease": "Lease-Verfügbarkeit prüfen",
  "safety.checksum": "SHA-256",
  "safety.choose_user": "Berechtigten Benutzer auswählen",
  "safety.client_telemetry": "Client-Telemetrie (nicht vertrauenswürdig)",
  "safety.close": "Projektsicherheit schließen",
  "safety.collaboration": "Zusammenarbeit",
  "safety.companion": "Companion",
  "safety.companion_states_current": "Autorität aktuell",
  "safety.companion_states_incompatible": "Richtlinienversion nicht unterstützt",
  "safety.companion_states_refreshing": "Autorität wird aktualisiert",
  "safety.companion_states_stale": "Autorität veraltet",
  "safety.companion_states_unavailable": "Companion nicht verfügbar",
  "safety.confirm_access_body": "{member} auf {role} ändern, Zugriffsrevision {revision}? Die Änderung wird atomar übernommen und im vertrauenswürdigen Auditprotokoll festgehalten.",
  "safety.confirm_access_heading": "Zugriffsänderung bestätigen",
  "safety.confirm_apply_body": "{count} validierte Änderungen auf „{project}“ in Revision {revision} übernehmen? Zuerst wird ein verifiziertes Backup erstellt. Dies ändert nur Projektdaten und sendet keinen Anlagenbefehl.",
  "safety.confirm_apply_heading": "Projektänderungen bestätigen",
  "safety.confirm_remove_body": "Gesamten Zugriff für {member} entfernen, Zugriffsrevision {revision}? Es verbleibt keine Rolle in diesem Projekt.",
  "safety.conflict_body": "Revision {base} ist nicht mehr aktuell; Revision {current} ist aktiv. Ihr Entwurf bleibt im Speicher erhalten. Es wurde nichts überschrieben.",
  "safety.conflict_choices_discard": "Meine Änderungen verwerfen",
  "safety.conflict_choices_merge_preview": "Zusammenführung als Vorschau",
  "safety.conflict_choices_refresh": "Vom Server aktualisieren",
  "safety.conflict_choices_retry_with_fresh_lease": "Mit neuem Lease erneut versuchen",
  "safety.conflict_heading": "Speichern blockiert — es existiert eine neuere Revision",
  "safety.connected": "Verbunden",
  "safety.control_cancel": "Steuerung abbrechen",
  "safety.control_confirm_body": "„{label}“ ausführen? Der Companion löst die Wirkung aus dem aktuellen Projektstand auf; diese Karte sendet nur den Steuerungsnamen und die deklarierte Eingabe.",
  "safety.control_confirm_heading": "Konfigurierte Steuerung bestätigen",
  "safety.control_correlation": "Korrelations-ID",
  "safety.control_effect": "Aufgelöste Wirkung",
  "safety.control_heading": "Konfigurierte Steuerung",
  "safety.control_no_retry": "Diese Karte wiederholt eine Steuerung niemals von selbst. Entscheiden Sie erneut, wenn sich die Anlage bewegen soll.",
  "safety.control_policy": "Steuerungsrichtlinie",
  "safety.control_preview": "Steuerung als Vorschau",
  "safety.control_run": "Steuerung ausführen",
  "safety.control_states_accepted": "Angenommen und protokolliert. Noch nicht abgesetzt.",
  "safety.control_states_cancelled_before_dispatch": "Abgebrochen. Es wurde nichts gesendet.",
  "safety.control_states_denied": "Abgelehnt.",
  "safety.control_states_dispatched": "An Home Assistant abgesetzt. Noch nicht bestätigt.",
  "safety.control_states_failed_after_dispatch": "Nach dem Absetzen fehlgeschlagen. Die Wirkung ist unbekannt — prüfen Sie den aktuellen Zustand und das vertrauenswürdige Auditprotokoll.",
  "safety.control_states_failed_before_dispatch": "Vor dem Absetzen fehlgeschlagen. Es wurde nichts gesendet.",
  "safety.control_states_readback_confirmed": "Durch Rücklesung bestätigt.",
  "safety.control_states_result_unknown": "Das Ergebnis ist unbekannt — prüfen Sie den aktuellen Zustand und das vertrauenswürdige Auditprotokoll, bevor Sie erneut handeln.",
  "safety.control_states_timed_out": "Zeitüberschreitung. Die Wirkung ist unbekannt — prüfen Sie den aktuellen Zustand und das vertrauenswürdige Auditprotokoll.",
  "safety.control_target": "Ziel",
  "safety.controls_visible": "{count} für Sie sichtbare Steuerungen",
  "safety.current_revision": "Revision",
  "safety.discard_body": "Die ungespeicherten Änderungen dieser Sitzung verwerfen? Sie können danach nicht wiederhergestellt werden.",
  "safety.discard_heading": "Ungespeicherte Änderungen verwerfen",
  "safety.dry_run": "Probelauf starten",
  "safety.dry_run_fresh": "Neuen Probelauf starten",
  "safety.editing": "Bearbeitung",
  "safety.eligible_user": "Berechtigter Benutzer",
  "safety.error_codes_authority_stale": "Die Serverautorität ist veraltet. Aktualisieren Sie und versuchen Sie es erneut.",
  "safety.error_codes_capability_denied": "Ihre Rolle erlaubt diese Aktion nicht.",
  "safety.error_codes_effect_unknown": "Das Ergebnis ist unbekannt. Prüfen Sie das vertrauenswürdige Auditprotokoll vor einem erneuten Versuch.",
  "safety.error_codes_feature_unavailable": "Diese Funktion ist in dieser Version nicht verfügbar.",
  "safety.error_codes_invalid_input": "Die Anfrage wurde als ungültig abgelehnt. Es wurde nichts geändert.",
  "safety.error_codes_lease_expired": "Das Bearbeitungslease ist abgelaufen.",
  "safety.error_codes_lease_held": "Eine andere Sitzung bearbeitet gerade.",
  "safety.error_codes_lease_required": "Ein Bearbeitungslease ist erforderlich.",
  "safety.error_codes_not_found_or_denied": "Dieses Projekt ist für Sie nicht verfügbar.",
  "safety.error_codes_not_loaded": "Der Companion ist nicht geladen.",
  "safety.error_codes_rate_limited": "Zu viele Anfragen. Warten Sie und versuchen Sie es erneut.",
  "safety.error_codes_revision_conflict": "Es existiert eine neuere Revision. Ihr Entwurf bleibt erhalten.",
  "safety.errors": "Validierungsprobleme",
  "safety.exact_card_version": "Exakte Kartenversion",
  "safety.expected_revision": "Erwartet",
  "safety.export_telemetry": "Client-Telemetrie exportieren",
  "safety.export_trusted": "Vertrauenswürdiges Auditprotokoll exportieren",
  "safety.ignored_noise": "Ignorierte Reihenfolgenänderung",
  "safety.impact": "Auswirkung",
  "safety.inspect_bundle": ".gltproject-Paket prüfen",
  "safety.last_refresh": "Letzte Aktualisierung",
  "safety.lease_acquiring": "Exklusives Bearbeitungslease wird angefordert",
  "safety.lease_expires_in": "Läuft in {seconds}s ab",
  "safety.lease_heading": "Bearbeitungslease",
  "safety.lease_renew_due": "Die Verlängerung ist fällig. Verlängern Sie vor Ablauf des Leases.",
  "safety.lease_states_available": "Lease verfügbar",
  "safety.lease_states_expired": "Lease abgelaufen",
  "safety.lease_states_held_other": "Eine andere Sitzung bearbeitet",
  "safety.lease_states_held_self": "Diese Sitzung",
  "safety.lease_states_lost": "Lease verloren",
  "safety.lease_states_read_only": "Schreibgeschützt",
  "safety.lease_states_renewing": "Wird verlängert",
  "safety.load_next": "Nächste 50 Ereignisse laden",
  "safety.manage_access": "Projektzugriff verwalten",
  "safety.media_type": "Medientyp",
  "safety.member_column": "Mitglied",
  "safety.merge_states_applied": "Zusammenführung übernommen",
  "safety.merge_states_blocked": "Dieselben Pfade wurden auf beiden Seiten geändert. Wählen Sie eine andere Wiederherstellung.",
  "safety.merge_states_failed": "Die Zusammenführungsvorschau ist fehlgeschlagen. Ihr Entwurf bleibt unverändert.",
  "safety.merge_states_idle": "Keine Zusammenführungsvorschau angefordert.",
  "safety.merge_states_ready": "Zusammenführungsvorschau bereit. Wählen Sie die zu behaltenden Änderungen.",
  "safety.merge_states_requested": "Zusammenführungsvorschau wird angefordert",
  "safety.mode_local": "Nur lokales Projekt",
  "safety.mode_shared": "Gemeinsames Projekt",
  "safety.my_access": "Mein Zugriff",
  "safety.my_role": "Meine Rolle",
  "safety.never": "Nie",
  "safety.no_capabilities": "Keine Berechtigungen in diesem Projekt.",
  "safety.no_evidence": "Die Release-Nachweise sind unvollständig. Fehlende oder veraltete Prüfungen sind unten aufgeführt.",
  "safety.not_evidence": "Kein Sicherheits- oder Steuerungsnachweis",
  "safety.not_run": "Nicht ausgeführt",
  "safety.overview": "Übersicht Projektsicherheit",
  "safety.path": "Pfad",
  "safety.policy_version": "Richtlinienversion",
  "safety.preview_failed": "Die Migrationsvorschau ist fehlgeschlagen. Das Originalprojekt bleibt unverändert. Prüfen Sie die Diagnose und starten Sie einen neuen Probelauf.",
  "safety.preview_ready": "Migrationsvorschau bereit",
  "safety.project": "Projekt",
  "safety.raw_contract": "Rohvertrag",
  "safety.read_only": "Schreibgeschützt",
  "safety.read_only_reasons_authority_absent": "Noch keine Serverautorität. Gemeinsames Bearbeiten bleibt schreibgeschützt, bis der Companion antwortet.",
  "safety.read_only_reasons_authority_incompatible": "Der Companion verwendet eine Richtlinienversion, die diese Karte nicht unterstützt.",
  "safety.read_only_reasons_authority_loading": "Serverautorität wird aktualisiert. Bearbeiten ist bis dahin schreibgeschützt.",
  "safety.read_only_reasons_authority_rejected": "Der Companion hat die Aktualisierung der Autorität abgelehnt. Gemeinsames Bearbeiten ist schreibgeschützt.",
  "safety.read_only_reasons_authority_sequence_gap": "Eine Autoritätsaktualisierung wurde verpasst. Vor dem Bearbeiten aktualisieren.",
  "safety.read_only_reasons_authority_stale": "Die Serverautorität ist veraltet. Vor dem Bearbeiten aktualisieren.",
  "safety.read_only_reasons_companion_disconnected": "Der Companion ist nicht verfügbar. Gemeinsames Bearbeiten ist schreibgeschützt.",
  "safety.read_only_reasons_lease_expired": "Das Bearbeitungslease ist abgelaufen. Ihr ungespeicherter Entwurf bleibt erhalten.",
  "safety.read_only_reasons_lease_lost": "Das Bearbeitungslease ging verloren. Ihr ungespeicherter Entwurf bleibt erhalten.",
  "safety.read_only_reasons_lease_required": "Fordern Sie das Bearbeitungslease an, um Änderungen vorzunehmen.",
  "safety.read_only_reasons_role_missing": "Sie haben keine Rolle in diesem Projekt.",
  "safety.read_only_reasons_role_revoked": "Ihre Rolle für dieses Projekt hat sich geändert. Gemeinsames Bearbeiten ist schreibgeschützt.",
  "safety.release_evidence": "Release-Nachweise",
  "safety.release_lease": "Bearbeitungslease freigeben",
  "safety.remove_access": "Zugriff entfernen",
  "safety.renew_lease": "Bearbeitungslease verlängern",
  "safety.required_dependency": "Erforderliche Abhängigkeit",
  "safety.restore": "Verifiziertes Backup wiederherstellen",
  "safety.restore_awaiting": "Geben Sie „{project}“ ein, um „Verifiziertes Backup wiederherstellen“ zu aktivieren.",
  "safety.restore_body": "Verifiziertes Backup {backup_id} für „{project}“ wiederherstellen? Die aktuelle Revision {revision} wird ersetzt. Ein neuer Nachweis wird erstellt. Dies ändert nur Projektdaten und sendet keinen Anlagenbefehl.",
  "safety.restore_label": "Projektname zur Bestätigung eingeben",
  "safety.restore_mismatch": "Der Projektname stimmt nicht überein. Das Projekt bleibt unverändert.",
  "safety.restore_ready": "Projektname bestätigt. Prüfen Sie vor dem Fortfahren die Revision und das Backup.",
  "safety.revision": "Revision",
  "safety.revision_conflict": "Revision {expected} ist nicht mehr aktuell; Revision {actual} ist aktiv. Laden Sie neu und vergleichen Sie erneut.",
  "safety.revision_triplet": "Basis {base} · Aktuell {current} · Entwurf {candidate}",
  "safety.role_column": "Rolle",
  "safety.role_matrix": "Rollen-Berechtigungsmatrix",
  "safety.role_matrix_unavailable": "Der Companion hat für diese Rolle keine Berechtigungsmatrix zurückgegeben.",
  "safety.role_names_admin": "Administrator",
  "safety.role_names_engineer": "Ingenieur",
  "safety.role_names_none": "Keine Zuweisung",
  "safety.role_names_operator": "Bediener",
  "safety.role_names_viewer": "Betrachter",
  "safety.rollback_failure": "Verifizierung der Backup-Wiederherstellung fehlgeschlagen. Beide Snapshots wurden beibehalten. Laden Sie die Rollback-Diagnose herunter und fordern Sie eine Wiederherstellung durch die Administration an.",
  "safety.rollback_running": "Verifiziertes Backup wird wiederhergestellt",
  "safety.rollback_success": "Verifiziertes Backup wiederhergestellt",
  "safety.rollback_success_body": "Projektrevision {revision} entspricht dem verifizierten Backup {backup_id}. Ein Rollback-Nachweis wurde erstellt.",
  "safety.rows_stale": "Die nächste Seite konnte nicht geladen werden. Die angezeigten Ereignisse sind nicht mehr aktuell.",
  "safety.schema": "Schema",
  "safety.scope": "Nur Projektdaten — es wird kein Home-Assistant-Dienst und kein Anlagenbefehl ausgeführt.",
  "safety.server_authored": "Serverseitig erzeugt",
  "safety.server_normalization": "Servernormalisierung aktiv",
  "safety.shared_authority": "Gemeinsame Autorität",
  "safety.size": "Größe",
  "safety.standalone": "Companion nicht verfügbar — gemeinsame Projektaktionen sind schreibgeschützt.",
  "safety.tabs_0": "Übersicht",
  "safety.tabs_1": "Validieren",
  "safety.tabs_2": "Migrieren & vergleichen",
  "safety.tabs_3": "Pakete",
  "safety.tabs_4": "Nachweise",
  "safety.telemetry_category": "Kategorie",
  "safety.telemetry_empty": "In dieser Sitzung wurde keine Client-Telemetrie aufgezeichnet.",
  "safety.telemetry_payload": "Nutzdaten-Zusammenfassung",
  "safety.telemetry_received": "Empfangen",
  "safety.title": "Projektsicherheit",
  "safety.trusted_audit": "Vertrauenswürdiges Auditprotokoll",
  "safety.trusted_empty": "Für Sie ist noch kein vertrauenswürdiges Auditereignis sichtbar.",
  "safety.unchanged": "Originalprojekt unverändert",
  "safety.validate": "Projekt validieren",
  "safety.validation_failed": "Projektvalidierung fehlgeschlagen",
  "safety.validation_idle": "Wählen Sie „Projekt validieren“, um das Rohprojekt unverändert zu prüfen.",
  "safety.validation_invalid": "Das Projekt ist ungültig. Prüfen Sie die aufgeführten Pfade; das Original bleibt unverändert.",
  "safety.validation_running": "Rohprojekt wird validiert",
  "safety.validation_success": "Projektvalidierung abgeschlossen",
  "safety.validation_valid": "Keine Validierungsprobleme gefunden. Das Rohprojekt entspricht Schema {version}.",
  "safety.workflow_0": "Prüfen",
  "safety.workflow_1": "Vorschau",
  "safety.workflow_2": "Backup",
  "safety.workflow_3": "Übernehmen",
  "safety.workflow_4": "Verifizieren",
  "sites.age": "Stand vor {seconds} s",
  "sites.completeness": "{answered} von {total} Standorten geantwortet",
  "sites.effect_unknown": "Wirkung unbekannt — der Befehl kann ausgeführt worden sein. Prüfen Sie den Anlagenzustand, bevor Sie etwas erneut senden.",
  "sites.missing_sites": "Fehlende Standorte:",
  "sites.no_value": "kein Messwert",
  "sites.shape_circuit_open": "✕",
  "sites.shape_healthy": "●",
  "sites.shape_slow": "◐",
  "sites.shape_unreachable": "○",
  "sites.site_circuit_open": "ausgesetzt nach wiederholten Fehlern",
  "sites.site_healthy": "erreichbar",
  "sites.site_slow": "langsam",
  "sites.site_unreachable": "nicht erreichbar",
  "sites.unverified_tls": "unverschlüsselt geprüft: Zertifikat wird für diesen Standort nicht geprüft",
  "trends.coverage": "Abdeckung {percent} %",
  "trends.coverage_gaps": "Abdeckung {percent} % · {gaps} {gapWord}",
  "trends.gap_one": "Lücke",
  "trends.gap_other": "Lücken",
  "trends.gap_row": "Keine Daten von {start} bis {end}",
  "trends.no_data": "Keine Daten",
  "trends.span_day23": "Dieser Tag hat 23 Stunden — die Zeitumstellung fällt hinein.",
  "trends.span_day25": "Dieser Tag hat 25 Stunden — die Zeitumstellung fällt hinein.",
  "trends.span_month": "Dieser Monat hat {hours} Stunden — die Zeitumstellung fällt hinein.",
  "trends.unreadable": "Nicht lesbar",
});

registerCatalog("de", ENTRIES);
