"""Resolve a named period to a start and an end, in the site timezone.

The whole of this module is a delegation, and that is the point.

``07-RESEARCH.md`` measured what Home Assistant already does. Its statistics
period reducers build their boundaries with
``datetime.fromtimestamp(tz=dt_util.get_default_time_zone())`` -- local
midnights, not UTC epoch multiples -- and ``resolve_period`` answers a
``CalendarStatisticPeriod`` the same way. For ``Europe/Berlin`` a spring-forward
day is 23 hours, a fall-back day is 25, and October 2027 is 745 hours rather
than 744.

What ships instead is ``Math.floor(x / bucketMs) * bucketMs`` (D9). That is
always exactly ``bucketMs`` long and aligned to the UTC epoch, so every "daily"
bucket is displaced by one or two hours year-round and, on a transition day,
contains an hour too much or too little of the wrong day. ``bucket_minutes``
cannot express a month at all, and the report designer offers months and years.

So this module **names, validates and renders** a period. It never computes one.
The arithmetic below exists only to reproduce Home Assistant's own boundaries
without importing the Recorder into a code path that must also run when the
Recorder is unavailable -- and ``test_period_resolution.py`` compares every
result against a corpus generated by executing the vendored implementation, so a
divergence between this and Home Assistant fails rather than drifts.

Two contracts answer these periods, and which one is not a detail: ``day``,
``week`` and ``month`` go to ``recorder/statistics_during_period``, whose
``period`` enum stops there, and ``year`` is reachable only through
``recorder/statistic_during_period``'s calendar spec. Reading the plural command
alone concludes, wrongly, that the product must aggregate years itself.
"""
from __future__ import annotations

import json
from datetime import date, datetime, timedelta
from typing import Any
from datetime import timezone as _timezone
from zoneinfo import ZoneInfo

from .measured_value import canonical_number
from .period_vocabulary import FIRST_WEEKDAYS, contract_for, is_first_weekday

#: The corpus spec names, mapped to what each asks for. Kept here rather than
#: parsed out of the spec string, so an unknown spec is refused rather than
#: silently interpreted as its nearest match.
SPECS: dict[str, dict[str, Any]] = {
    "day": {"kind": "calendar", "offset": 0, "period": "day"},
    "day-previous": {"kind": "calendar", "offset": -1, "period": "day"},
    "week-mon": {"first_weekday": "mon", "kind": "calendar", "offset": 0, "period": "week"},
    "week-sun": {"first_weekday": "sun", "kind": "calendar", "offset": 0, "period": "week"},
    "month": {"kind": "calendar", "offset": 0, "period": "month"},
    "month-previous": {"kind": "calendar", "offset": -1, "period": "month"},
    "year": {"kind": "calendar", "offset": 0, "period": "year"},
    "year-previous": {"kind": "calendar", "offset": -1, "period": "year"},
    "rolling-24h": {"hours": 24, "kind": "rolling"},
}

_WEEKDAY_INDEX = {name: index for index, name in enumerate(FIRST_WEEKDAYS)}


def _zone(timezone: str) -> ZoneInfo:
    try:
        return ZoneInfo(timezone)
    except Exception as error:  # noqa: BLE001 - the reason is the useful part
        raise ValueError(f"unknown site timezone: {timezone!r}") from error


def _local_midnight(day: date, zone: ZoneInfo) -> datetime:
    """Return local midnight on a calendar day.

    Takes a ``date`` rather than a ``datetime`` on purpose. Adding a
    ``timedelta`` to a zone-aware datetime does **wall-clock** arithmetic and
    keeps the original offset, so 2027-10-31T00:00+02:00 plus one day is
    2027-11-01T00:00+02:00 -- an offset that does not exist on that date, and a
    span of 24 hours where the calendar day was 25.

    That is the exact defect this module exists to fix, arriving from the other
    side: the shipped code gets a constant-length bucket by dividing epoch
    milliseconds, and the obvious replacement gets a constant-length bucket by
    adding a timedelta. Doing the arithmetic on calendar days and letting the
    zone decide the offset is the only form that yields 23 and 25.
    """
    return datetime(day.year, day.month, day.day, tzinfo=zone)


def _add_months(day: date, months: int) -> date:
    total = day.year * 12 + (day.month - 1) + months
    return date(total // 12, total % 12 + 1, 1)


def _calendar_bounds(spec: dict[str, Any], now: datetime, zone: ZoneInfo) -> tuple[datetime, datetime]:
    period = spec["period"]
    offset = int(spec.get("offset", 0))
    today = now.date()

    if period == "day":
        first = today + timedelta(days=offset)
        return _local_midnight(first, zone), _local_midnight(first + timedelta(days=1), zone)

    if period == "week":
        first_weekday = spec.get("first_weekday", "mon")
        if not is_first_weekday(first_weekday):
            raise ValueError(f"unknown first weekday: {first_weekday!r}")
        # Python's weekday() is Monday=0 and FIRST_WEEKDAYS is ordered from
        # Monday, so the index is the same number by construction rather than by
        # a table that could drift out of step with the vocabulary.
        delta = (today.weekday() - _WEEKDAY_INDEX[first_weekday]) % 7
        first = today - timedelta(days=delta) + timedelta(weeks=offset)
        return _local_midnight(first, zone), _local_midnight(first + timedelta(days=7), zone)

    if period == "month":
        first = _add_months(today.replace(day=1), offset)
        return _local_midnight(first, zone), _local_midnight(_add_months(first, 1), zone)

    if period == "year":
        first = date(today.year + offset, 1, 1)
        return _local_midnight(first, zone), _local_midnight(date(first.year + 1, 1, 1), zone)

    raise ValueError(f"unknown_period: {period!r}")


def resolve(spec: str, *, now: str, timezone: str) -> dict[str, Any]:
    """Resolve one named period against a moment, in the site timezone.

    Returns the boundaries as canonical strings with their offsets, plus the
    span in hours -- which is the field that makes a wrong answer visible. A
    resolver that is an hour out still produces plausible timestamps; it cannot
    produce a 23-hour day on the wrong date.
    """
    if spec not in SPECS:
        raise ValueError(f"unknown_period: {spec!r}")
    zone = _zone(timezone)
    moment = datetime.fromisoformat(now).astimezone(zone)
    shape = SPECS[spec]

    if shape["kind"] == "rolling":
        end = moment
        # Subtracted in UTC, then brought back. A timedelta subtracted from a
        # zone-aware datetime is wall-clock arithmetic: 24 hours before
        # 2027-10-31T12:00+01:00 comes out as 12:00+02:00 on the 30th, which is
        # 25 elapsed hours, not 24. A rolling window is a duration, so it is
        # measured where durations are unambiguous.
        start = (
            end.astimezone(_timezone.utc) - timedelta(hours=int(shape["hours"]))
        ).astimezone(zone)
    else:
        start, end = _calendar_bounds(shape, moment, zone)

    return {
        "end": canonical_instant(end, zone),
        "spec": spec,
        "span_hours": _span_hours(start, end),
        "start": canonical_instant(start, zone),
        "timezone": timezone,
    }


def _span_hours(start: datetime, end: datetime) -> float:
    """Return the elapsed hours between two instants.

    Both are converted to UTC first, and that is load-bearing rather than
    defensive. CPython's ``datetime.__sub__`` short-circuits when both operands
    share the same ``tzinfo`` object and subtracts them as if they were naive,
    so ``datetime(2027, 11, 1, tzinfo=BER) - datetime(2027, 10, 31, tzinfo=BER)``
    is 24 hours even though the two instants are 25 hours apart and their
    offsets, +01:00 and +02:00, say so on their face.

    The boundaries were already correct when this was wrong. Only the span was
    off, by exactly the hour the whole phase is about, and it is a plausible
    number that no assertion about the shape of the result would have caught.
    """
    utc_start = start.astimezone(_timezone.utc)
    utc_end = end.astimezone(_timezone.utc)
    return canonical_number(round((utc_end - utc_start).total_seconds() / 3600, 4))


def canonical_instant(moment: datetime, zone: ZoneInfo | None = None) -> str:
    """Render an instant the way both runtimes must agree on it.

    Seconds precision with an explicit offset. Phase 6 lost a cycle to
    ``toISOString()`` writing milliseconds where ``isoformat()`` omits them at
    zero, and 07-02 lost one to ``0`` against ``0.0``. Fixing the representation
    where the value is produced is the only version of that lesson that holds.
    """
    if zone is not None:
        moment = moment.astimezone(zone)
    return moment.replace(microsecond=0).isoformat()


def canonical(resolved: dict[str, Any]) -> str:
    """Return the canonical bytes both runtimes must agree on."""
    return json.dumps(resolved, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


#: Which bucket a named window is measured in. Closed, and a table rather than
#: a computation, because this is the decision Phase 7 deliberately left open
#: instead of half-building.
#:
#: The window and the bucket are different things, and conflating them is how a
#: grid gets invented. A month asked for at daily resolution has 28 to 31
#: buckets; the same month asked for hourly has 743, 744 or 745. Neither number
#: is derivable from the other without saying which resolution was meant.
#:
#: Deriving the grid from the rows that came *back* is the defect
#: ``expected_instants`` exists to prevent: the Recorder omits an empty period
#: entirely, so a month with nine missing days returns 22 rows and a grid built
#: from them says the month had 22 days and full coverage.
BUCKET_STEPS: dict[str, str] = {
    "day": "hour",
    "day-previous": "hour",
    "rolling-24h": "hour",
    "week-mon": "day",
    "week-sun": "day",
    "month": "day",
    "month-previous": "day",
    "year": "month",
    "year-previous": "month",
}

#: The three step models. An hour is a *duration*; a day and a month are
#: *calendar* steps. That distinction is the whole content of this module and it
#: is why the grid cannot be `range(0, n)` over a constant.
BUCKET_MODELS: tuple[str, ...] = ("hour", "day", "month")

#: A bound on the grid itself. The largest legitimate grid here is a year of
#: months (12) or a fall-back day of hours (25), so anything approaching this is
#: a stepping bug that would otherwise spin.
MAX_BUCKETS = 10_000


def bucket_for(spec: str) -> str:
    """Return the bucket step a named window is measured in, or refuse."""
    if spec not in BUCKET_STEPS:
        raise ValueError(f"unknown_period: {spec!r}")
    return BUCKET_STEPS[spec]


def expected_instants(spec: str, *, now: str, timezone: str) -> list[str]:
    """Return the bucket boundaries a named window *should* produce.

    This is the grid the answer is measured against: what came back is compared
    to what was asked for, and the difference is the coverage. It is computed
    from the period, never from the response.

    Each step is taken in the model that step belongs to. An hour is added in
    UTC, because an hour is an hour on both sides of a transition and only its
    wall-clock label moves -- which is exactly why a 23-hour day yields 23
    hourly instants and a 25-hour day yields 25. A day and a month are stepped
    on the calendar and handed back to the zone, because adding a timedelta to
    an aware datetime is wall-clock arithmetic that keeps the original offset
    and would produce a 24-hour day where the calendar says 23.
    """
    step = bucket_for(spec)
    zone = _zone(timezone)
    resolved = resolve(spec, now=now, timezone=timezone)
    cursor = datetime.fromisoformat(resolved["start"]).astimezone(zone)
    finish = datetime.fromisoformat(resolved["end"]).astimezone(zone)

    instants: list[str] = []
    while cursor < finish:
        instants.append(canonical_instant(cursor, zone))
        if len(instants) > MAX_BUCKETS:
            raise ValueError(f"bucket grid exceeded {MAX_BUCKETS} steps for {spec!r}")
        if step == "hour":
            cursor = (cursor.astimezone(_timezone.utc) + timedelta(hours=1)).astimezone(zone)
        elif step == "day":
            cursor = _local_midnight(cursor.date() + timedelta(days=1), zone)
        else:
            cursor = _local_midnight(_add_months(cursor.date(), 1), zone)
    return instants


def canonical_grid(spec: str, instants: list[str]) -> str:
    """Return the canonical bytes both runtimes must agree on for one grid."""
    return json.dumps(
        {"count": len(instants), "instants": instants, "spec": spec},
        ensure_ascii=False, separators=(",", ":"), sort_keys=True,
    )


def contract_for_spec(spec: str) -> str:
    """Return which Recorder contract answers this spec, or refuse."""
    if spec not in SPECS:
        raise ValueError(f"unknown_period: {spec!r}")
    shape = SPECS[spec]
    if shape["kind"] == "rolling":
        return "either"
    return contract_for(shape["period"])
