/* Independently rebuild and verify committed release artifacts and drift failures. */
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import {
  appendFile,
  cp,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const MANIFEST_PATH = "custom_components/glt_flow_card/build-manifest.json";
const STAGING_MANIFEST_PATH = path.join(path.dirname(fileURLToPath(import.meta.url)), "../build/release/hacs-staging-manifest.json");

//: Staged paths that are copied verbatim from the repository, and must
//: therefore be byte-identical to the artifacts this run just verified.
const SHIPPED_PREFIXES = ["custom_components/glt_flow_card/", "dist/"];
const OUTPUT_PATHS = [
  MANIFEST_PATH,
  "custom_components/glt_flow_card/schemas/bundle-manifest.schema.json",
  "custom_components/glt_flow_card/schemas/diff-policy.json",
  "custom_components/glt_flow_card/schemas/limits.json",
  "custom_components/glt_flow_card/schemas/project/0.schema.json",
  "custom_components/glt_flow_card/schemas/project/1.schema.json",
  "custom_components/glt_flow_card/schemas/project/2.schema.json",
  "custom_components/glt_flow_card/www/glt-flow-card.js",
  "dist/glt-flow-card.js",
  "dist/schemas/bundle-manifest.schema.json",
  "dist/schemas/diff-policy.json",
  "dist/schemas/limits.json",
  "dist/schemas/project/0.schema.json",
  "dist/schemas/project/1.schema.json",
  "dist/schemas/project/2.schema.json",
  "docs/editor/app.js",
];
const SCHEMAS = [
  ["bundleManifest", "schemas/bundle-manifest.schema.json"],
  ["diffPolicy", "schemas/diff-policy.json"],
  ["limits", "schemas/limits.json"],
  ["project0", "schemas/project/0.schema.json"],
  ["project1", "schemas/project/1.schema.json"],
  ["project2", "schemas/project/2.schema.json"],
];
const DEFAULT_EVIDENCE_PATH = path.join(ROOT, ".planning/tmp/release-build-verification.json");

function parseArgs(argv) {
  let evidencePath = DEFAULT_EVIDENCE_PATH;
  for (const argument of argv) {
    if (argument.startsWith("--evidence=")) {
      evidencePath = path.resolve(ROOT, argument.slice("--evidence=".length));
      continue;
    }
    throw new Error(`unknown release verification argument: ${argument}`);
  }
  return { evidencePath };
}

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (!value || typeof value !== "object") return value;
  return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])]));
}

function canonicalJson(value) {
  return `${JSON.stringify(canonical(value), null, 2)}\n`;
}

function git(args) {
  const result = spawnSync("git", args, { cwd: ROOT, encoding: "utf8" });
  return result.status === 0 ? result.stdout.trim() : "";
}

async function walkFiles(root, relativeDirectory = "") {
  const directory = path.join(root, relativeDirectory);
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (error.code === "ENOENT") return [];
    throw error;
  }
  const files = [];
  for (const entry of entries) {
    const relativePath = path.posix.join(relativeDirectory.replaceAll("\\", "/"), entry.name);
    if (entry.isDirectory()) files.push(...await walkFiles(root, relativePath));
    if (entry.isFile()) files.push(relativePath);
  }
  return files.sort();
}

async function requireOutputSet(outputRoot) {
  const actual = await walkFiles(outputRoot);
  const missing = OUTPUT_PATHS.filter((relativePath) => !actual.includes(relativePath));
  if (missing.length) throw new Error(`missing generated output: ${missing[0]}`);
  const unexpected = actual.filter((relativePath) => !OUTPUT_PATHS.includes(relativePath));
  if (unexpected.length) throw new Error(`unexpected generated output: ${unexpected[0]}`);
}

function runBuild(outputRoot) {
  const result = spawnSync(
    process.execPath,
    ["tools/build.mjs", "--output-root", outputRoot],
    { cwd: ROOT, encoding: "utf8" },
  );
  if (result.status !== 0) {
    throw new Error(`isolated build failed:\n${result.stdout}\n${result.stderr}`);
  }
}

async function compareTrees(leftRoot, rightRoot, label, exactRight = true) {
  await requireOutputSet(leftRoot);
  if (exactRight) await requireOutputSet(rightRoot);
  for (const relativePath of OUTPUT_PATHS) {
    const left = await readFile(path.join(leftRoot, relativePath));
    const right = await readFile(path.join(rightRoot, relativePath));
    if (!left.equals(right)) throw new Error(`${label}: generated bytes differ: ${relativePath}`);
  }
}

async function verifyOutput(outputRoot, exactSet = true) {
  if (exactSet) await requireOutputSet(outputRoot);
  const manifestBytes = await readFile(path.join(outputRoot, MANIFEST_PATH));
  const manifest = JSON.parse(manifestBytes);
  if (manifestBytes.toString("utf8") !== canonicalJson(manifest)) {
    throw new Error("build manifest is not canonical JSON");
  }
  if (manifest.format !== "glt-flow-card-build-manifest" || manifest.manifest_version !== 1) {
    throw new Error("build manifest format/version disagreement");
  }

  const packageJson = require(path.join(ROOT, "package.json"));
  const companionManifest = JSON.parse(await readFile(
    path.join(ROOT, "custom_components/glt_flow_card/manifest.json"),
    "utf8",
  ));
  const dist = await readFile(path.join(outputRoot, "dist/glt-flow-card.js"));
  const companion = await readFile(path.join(
    outputRoot,
    "custom_components/glt_flow_card/www/glt-flow-card.js",
  ));
  const cardVersion = dist.toString("utf8").match(/const VERSION = "([^"]+)";/)?.[1];
  if (
    cardVersion !== packageJson.version
    || companionManifest.version !== packageJson.version
    || manifest.versions.card !== packageJson.version
    || manifest.versions.companion !== packageJson.version
    || manifest.versions.package !== packageJson.version
  ) {
    throw new Error("card/package version disagreement");
  }
  for (const [schemaName, sourcePath] of SCHEMAS) {
    const canonicalBytes = await readFile(path.join(ROOT, sourcePath));
    JSON.parse(canonicalBytes);
    const outputPaths = [
      sourcePath.replace(/^schemas\//, "dist/schemas/"),
      sourcePath.replace(/^schemas\//, "custom_components/glt_flow_card/schemas/"),
    ];
    for (const outputPath of outputPaths) {
      const outputBytes = await readFile(path.join(outputRoot, outputPath));
      if (!outputBytes.equals(canonicalBytes)) throw new Error(`canonical schema drift: ${outputPath}`);
    }
    if (manifest.schemas[schemaName] !== sha256(canonicalBytes)) {
      throw new Error(`schema fingerprint mismatch: ${sourcePath}`);
    }
  }

  const expectedArtifactPaths = OUTPUT_PATHS.filter((relativePath) => relativePath !== MANIFEST_PATH);
  if (canonicalJson(manifest.artifacts.map(({ path: relativePath }) => relativePath))
      !== canonicalJson(expectedArtifactPaths)) {
    throw new Error("manifest artifact path set disagreement");
  }
  for (const artifact of manifest.artifacts) {
    const bytes = await readFile(path.join(outputRoot, artifact.path));
    if (artifact.sha256 !== sha256(bytes) || artifact.size !== bytes.length) {
      throw new Error(`artifact hash mismatch: ${artifact.path}`);
    }
  }
  if (!dist.equals(companion)) throw new Error("dist/www byte inequality");

  const requiredSources = [
    "src/generated-bases/editor-app.base.js",
    "src/generated-bases/glt-flow-card.base.js",
    "tools/apply-v100.mjs",
    "tools/build.mjs",
    "tools/generate-project-validators.mjs",
  ];
  const sourcePaths = manifest.sources.map(({ path: sourcePath }) => sourcePath);
  for (const requiredSource of requiredSources) {
    if (!sourcePaths.includes(requiredSource)) throw new Error(`manifest source missing: ${requiredSource}`);
  }
  for (const source of manifest.sources) {
    if (path.isAbsolute(source.path) || source.path.includes("..")) {
      throw new Error(`unsafe manifest source path: ${source.path}`);
    }
    const bytes = await readFile(path.join(ROOT, source.path));
    if (source.sha256 !== sha256(bytes) || source.size !== bytes.length) {
      throw new Error(`source fingerprint mismatch: ${source.path}`);
    }
  }

  const expectedCommit = git(["log", "-1", "--format=%H", "--", ...sourcePaths]) || "WORKTREE";
  const expectedDirty = Boolean(git([
    "status",
    "--porcelain=v1",
    "--untracked-files=all",
    "--",
    ...sourcePaths,
  ]));
  if (manifest.build.commit !== expectedCommit || manifest.build.dirty !== expectedDirty) {
    throw new Error("manifest source commit/dirty marker disagreement");
  }
  if (
    manifest.tools.node !== "22"
    || manifest.tools.esbuild !== require("esbuild/package.json").version
    || manifest.tools.ajv !== require("ajv/package.json").version
  ) {
    throw new Error("manifest tool version disagreement");
  }

  const validator = await readFile(path.join(ROOT, "src/v100/generated/project-validators.mjs"));
  if (manifest.validator.sha256 !== sha256(validator) || manifest.validator.size !== validator.length) {
    throw new Error("validator compiler fingerprint mismatch");
  }
}

async function expectMutationFailure(name, sourceRoot, mutate, expectedMessage) {
  const mutationRoot = `${sourceRoot}-${name}`;
  await cp(sourceRoot, mutationRoot, { recursive: true });
  await mutate(mutationRoot);
  let message = "mutation unexpectedly passed";
  try {
    await verifyOutput(mutationRoot);
  } catch (error) {
    message = error.message;
  }
  if (!message.includes(expectedMessage)) {
    throw new Error(`${name} mutation expected "${expectedMessage}", received "${message}"`);
  }
  console.log(`PASS ${name}: ${expectedMessage}`);
}

async function updateArtifactDescriptor(outputRoot, relativePaths) {
  const manifestPath = path.join(outputRoot, MANIFEST_PATH);
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  for (const relativePath of relativePaths) {
    const bytes = await readFile(path.join(outputRoot, relativePath));
    const artifact = manifest.artifacts.find(({ path: artifactPath }) => artifactPath === relativePath);
    artifact.sha256 = sha256(bytes);
    artifact.size = bytes.length;
  }
  await writeFile(manifestPath, canonicalJson(manifest));
}

/**
 * Prove the staged packages are the checked-in bytes, without re-staging.
 *
 * The preflight verifies what will actually be shipped. Re-staging here would
 * only prove the stager is self-consistent; reading the stage the release will
 * upload proves it matches the artifacts this run just verified.
 */
async function verifyStageConsumesCheckedInBytes() {
  let manifest;
  try {
    manifest = JSON.parse(await readFile(STAGING_MANIFEST_PATH, "utf8"));
  } catch {
    throw new Error(
      "no staged packages found at build/release/hacs-staging-manifest.json. "
      + "Stage the packages first: this step consumes the stage, it never creates one.",
    );
  }
  if (manifest.format !== "glt-flow-card-hacs-staging-manifest" || manifest.manifest_version !== 1) {
    throw new Error("staged package manifest format/version disagreement");
  }
  let files = 0;
  for (const [name, entry] of Object.entries(manifest.packages ?? {})) {
    for (const descriptor of entry.files ?? []) {
      // Only the shipped artifacts are compared. A package README or hacs.json
      // is written for the package rather than copied from the repository, so
      // it has no checked-in counterpart to be stale against.
      if (!SHIPPED_PREFIXES.some((prefix) => descriptor.path.startsWith(prefix))) continue;
      const bytes = await readFile(path.join(ROOT, descriptor.path));
      if (bytes.length !== descriptor.size || sha256(bytes) !== descriptor.sha256) {
        throw new Error(`staged ${name} package is stale: ${descriptor.path}`);
      }
      files += 1;
    }
  }
  if (files === 0) throw new Error("staged packages reference no checked-in file");
  return { consumed: true, files };
}

async function main() {
  const { evidencePath } = parseArgs(process.argv.slice(2));
  const temporaryRoot = await mkdtemp(path.join(os.tmpdir(), "glt-release-verify-"));
  const firstRoot = path.join(temporaryRoot, "first");
  const secondRoot = path.join(temporaryRoot, "second");
  try {
    const validatorCheck = spawnSync(
      process.execPath,
      ["tools/generate-project-validators.mjs", "--check"],
      { cwd: ROOT, encoding: "utf8" },
    );
    if (validatorCheck.status !== 0) {
      throw new Error(`validator compiler drift: ${validatorCheck.stderr || validatorCheck.stdout}`);
    }
    runBuild(firstRoot);
    runBuild(secondRoot);
    await compareTrees(firstRoot, secondRoot, "double build");
    await verifyOutput(firstRoot);
    console.log("PASS double-build byte equality");

    await compareTrees(firstRoot, ROOT, "checked-in output", false);
    await verifyOutput(ROOT, false);
    console.log("PASS checked-in generated outputs");

    await expectMutationFailure(
      "one-byte",
      firstRoot,
      async (mutationRoot) => appendFile(path.join(mutationRoot, "dist/glt-flow-card.js"), Buffer.from([0])),
      "artifact hash mismatch: dist/glt-flow-card.js",
    );
    await expectMutationFailure(
      "version",
      firstRoot,
      async (mutationRoot) => {
        const paths = [
          "dist/glt-flow-card.js",
          "custom_components/glt_flow_card/www/glt-flow-card.js",
        ];
        for (const relativePath of paths) {
          const source = await readFile(path.join(mutationRoot, relativePath), "utf8");
          await writeFile(path.join(mutationRoot, relativePath), source.replace(
            'const VERSION = "1.0.0";',
            'const VERSION = "1.0.1";',
          ));
        }
        await updateArtifactDescriptor(mutationRoot, paths);
      },
      "card/package version disagreement",
    );
    await expectMutationFailure(
      "generated-source",
      firstRoot,
      async (mutationRoot) => appendFile(
        path.join(mutationRoot, "dist/schemas/project/2.schema.json"),
        " ",
      ),
      "canonical schema drift: dist/schemas/project/2.schema.json",
    );
    await expectMutationFailure(
      "missing-output",
      firstRoot,
      async (mutationRoot) => rm(path.join(mutationRoot, "docs/editor/app.js")),
      "missing generated output: docs/editor/app.js",
    );

    const buildManifestBytes = await readFile(path.join(ROOT, MANIFEST_PATH));
    const buildManifest = JSON.parse(buildManifestBytes);
    const stage = await verifyStageConsumesCheckedInBytes();
    console.log(`PASS staged package identity (${stage.files} files)`);
    const report = {
      build_manifest_sha256: sha256(buildManifestBytes),
      checked_in_outputs: { passed: true },
      double_build: { passed: true },
      format: "glt-flow-card-release-build-verification",
      report_version: 1,
      source_commit: buildManifest.build.commit,
      staged_packages: stage,
      verified: true,
    };
    await mkdir(path.dirname(evidencePath), { recursive: true });
    await writeFile(evidencePath, canonicalJson(report));
    console.log(`PASS release build evidence ${path.relative(ROOT, evidencePath)}`);
  } finally {
    await rm(temporaryRoot, { recursive: true, force: true });
  }
}

main().catch((error) => {
  console.error(`release verification failed: ${error.message}`);
  process.exitCode = 1;
});
