/**
 * Exact-dist Phase-2 authority and collaboration scenarios (T2-13, T2-14).
 *
 * Every test mounts the committed generated bytes and drives two isolated
 * browser contexts against one shared authoritative coordinator, so a lease, a
 * revision and a conflict are real rather than simulated.
 *
 * Grep groups: `authority`, `two-session`, `phase-2-fixture-seed`, `phase-2-ui`.
 */
import { expect, test } from "@playwright/test";

import {
  expectNoProhibitedEffects,
  formatEffectLedger,
  readEffectLedger,
  scanSeededSecrets,
} from "./fixtures/fake-ha.mjs";
import {
  ROLE_CAPABILITIES,
  STABLE_CODES,
  createSharedAuthority,
  installSharedAuthority,
} from "./fixtures/shared-authority.mjs";

const PROJECT = {
  type: "custom:glt-flow-card",
  schema_version: 2,
  title: "Exact-dist authority plant",
  project: { id: "authority-plant", name: "Authority Plant", revision: 4 },
  views: [{ id: "plant", name: "Plant", kind: "image" }],
  equipment: [{ id: "pump-1", name: "Pump 1", type: "pump" }],
  paths: [],
  datapoints: [],
};

const CONTROLS = [
  {
    id: "pump-1-start",
    label: "Start pump 1",
    domain: "switch",
    service: "turn_on",
    target: { entity_id: "switch.pump_1" },
    data: {},
  },
];

function authority() {
  return createSharedAuthority({
    project: PROJECT,
    members: { engineer: "engineer", engineer_two: "engineer", operator: "operator", viewer: "viewer" },
    controls: CONTROLS,
  });
}

async function mount(page, coordinator, options = {}) {
  const baseUrl = process.env.EXACT_DIST_BASE_URL;
  expect(baseUrl, "the exact-dist runner must provide a loopback URL").toMatch(
    /^http:\/\/127\.0\.0\.1:\d+\/$/,
  );
  const pageErrors = [];
  page.on("pageerror", (error) => pageErrors.push(error.message));
  const identity = await installSharedAuthority(page, coordinator, options);
  await page.goto(baseUrl, { waitUntil: "load" });
  await expect.poll(() => page.evaluate(() => window.__exactDistReady)).toBe(true);
  expect(pageErrors, "the release artifact must load without browser errors").toEqual([]);
  return identity;
}

// --------------------------------------------------------------------------
// Fixture guarantees. These prove the coordinator itself is trustworthy before
// any product behavior is asserted against it.
// --------------------------------------------------------------------------

test("authority fixture role matrix matches the server contract", () => {
  expect(ROLE_CAPABILITIES.viewer).not.toContain("project.write");
  expect(ROLE_CAPABILITIES.operator).toContain("control.execute");
  expect(ROLE_CAPABILITIES.operator).not.toContain("lease.engineering");
  expect(ROLE_CAPABILITIES.engineer).toContain("lease.engineering");
  expect(ROLE_CAPABILITIES.admin).toContain("project.access.write");
});

test("authority fixture answers hidden and missing projects identically", () => {
  const coordinator = authority();
  const hidden = coordinator.handle("outsider", "s1", {
    type: "glt_flow_card/projects/get",
    project_id: "authority-plant",
  });
  const missing = coordinator.handle("outsider", "s1", {
    type: "glt_flow_card/projects/get",
    project_id: "does-not-exist",
  });
  expect(hidden).toEqual(missing);
  expect(hidden.error.code).toBe("not_found_or_denied");
  expect(STABLE_CODES).toContain(hidden.error.code);
});

test("authority fixture grants exactly one exclusive engineering lease", () => {
  const coordinator = authority();
  const first = coordinator.handle("engineer", "s1", {
    type: "glt_flow_card/leases/acquire",
    ttl_seconds: 300,
  });
  expect(first.result.lease_token).toBeTruthy();

  const second = coordinator.handle("engineer_two", "s2", {
    type: "glt_flow_card/leases/acquire",
    ttl_seconds: 300,
  });
  expect(second.error.code).toBe("lease_held");
  expect(second.error).not.toHaveProperty("owner");
  expect(JSON.stringify(second)).not.toContain(first.result.lease_token);
});

test("authority fixture expires a lease with no grace period", () => {
  const coordinator = authority();
  const lease = coordinator.handle("engineer", "s1", {
    type: "glt_flow_card/leases/acquire",
    ttl_seconds: 60,
  }).result;

  coordinator.advance(59);
  const early = coordinator.handle("engineer", "s1", {
    type: "glt_flow_card/projects/apply",
    lease_token: lease.lease_token,
    expected_revision: 4,
    candidate: PROJECT,
  });
  expect(early.result.revision).toBe(5);

  coordinator.advance(2);
  const late = coordinator.handle("engineer", "s1", {
    type: "glt_flow_card/projects/apply",
    lease_token: lease.lease_token,
    expected_revision: 5,
    candidate: PROJECT,
  });
  expect(late.error.code).toBe("lease_expired");
});

test("two-session authority fixture produces a real revision conflict", () => {
  const coordinator = authority();
  const lease = coordinator.handle("engineer", "s1", {
    type: "glt_flow_card/leases/acquire",
    ttl_seconds: 300,
  }).result;
  coordinator.handle("engineer", "s1", {
    type: "glt_flow_card/projects/apply",
    lease_token: lease.lease_token,
    expected_revision: 4,
    candidate: PROJECT,
  });

  const stale = coordinator.handle("engineer", "s1", {
    type: "glt_flow_card/projects/apply",
    lease_token: lease.lease_token,
    expected_revision: 4,
    candidate: PROJECT,
  });
  expect(stale.error.code).toBe("revision_conflict");
  expect(stale.error.current_revision).toBe(5);
});

test("authority fixture refuses a caller-authored control target", () => {
  const coordinator = authority();
  const denied = coordinator.handle("operator", "s1", {
    type: "glt_flow_card/controls/execute",
    control_id: "pump-1-start",
    expected_revision: 4,
    entity_id: "switch.something_else",
  });
  expect(denied.error.code).toBe("invalid_input");
  expect(coordinator.inspect().serviceCalls).toEqual([]);
});

test("authority fixture resolves the whole control effect from its definition", () => {
  const coordinator = authority();
  const executed = coordinator.handle("operator", "s1", {
    type: "glt_flow_card/controls/execute",
    control_id: "pump-1-start",
    expected_revision: 4,
  });
  expect(executed.result.state).toBe("readback_confirmed");
  expect(coordinator.inspect().serviceCalls).toEqual([
    {
      domain: "switch",
      service: "turn_on",
      target: { entity_id: "switch.pump_1" },
      data: {},
      actor: "operator",
    },
  ]);
});

test("authority fixture invalidates every cursor and lease on restart", () => {
  const coordinator = authority();
  const lease = coordinator.handle("engineer", "s1", {
    type: "glt_flow_card/leases/acquire",
    ttl_seconds: 300,
  }).result;
  coordinator.restart();
  const after = coordinator.handle("engineer", "s1", {
    type: "glt_flow_card/projects/apply",
    lease_token: lease.lease_token,
    expected_revision: 4,
    candidate: PROJECT,
  });
  expect(after.error.code).toBe("lease_required");
  expect(coordinator.inspect().cursors).toBe(0);
});

test("authority fixture keeps remote routes fail-closed until Phase 9", () => {
  const coordinator = authority();
  for (const route of ["remote/list", "remote/states", "remote/control"]) {
    const response = coordinator.handle("engineer", "s1", { type: `glt_flow_card/${route}` });
    expect(response.error.code).toBe("feature_unavailable");
  }
});

// --------------------------------------------------------------------------
// Exact-dist seed scenario and the two product-completeness sentinels.
// --------------------------------------------------------------------------

test("phase-2-fixture-seed [expected-red:phase2-ui-fixture-seed] shared authority mounts the exact artifact", async ({
  browser,
}) => {
  const coordinator = authority();
  const contextOne = await browser.newContext();
  const contextTwo = await browser.newContext();
  const pageOne = await contextOne.newPage();
  const pageTwo = await contextTwo.newPage();

  try {
    const one = await mount(pageOne, coordinator, { actor: "engineer", session: "browser-a" });
    const two = await mount(pageTwo, coordinator, { actor: "engineer_two", session: "browser-b" });
    expect(one.session).not.toBe(two.session);

    // Both contexts load the same generated bytes and keep isolated storage.
    const identity = await pageOne.evaluate(() => window.__exactDistEvidence);
    expect(identity.dist_www_equal).toBe(true);
    expect(await pageTwo.evaluate(() => window.__exactDistEvidence)).toEqual(identity);

    await expectNoProhibitedEffects(pageOne);
    await expectNoProhibitedEffects(pageTwo);
    const ledger = await readEffectLedger(pageOne);
    console.log(formatEffectLedger("PHASE2_FIXTURE_EFFECTS ", ledger));

    const gaps = [];
    const authorityElement = await pageOne.evaluate(() =>
      Boolean(customElements.get("glt-flow-card-project-authority")),
    );
    if (!authorityElement) {
      gaps.push("the generated artifact registers no shared-authority surface");
    }
    if (gaps.length > 0) {
      console.log(
        "EXPECTED_RED[phase2-ui-fixture-seed]: exact-dist shared-authority UI is unavailable",
      );
      for (const gap of gaps) console.log(`  fixture gap: ${gap}`);
    }
    expect(gaps, "exact-dist shared-authority UI is unavailable").toEqual([]);
  } finally {
    await contextOne.close();
    await contextTwo.close();
  }
});

test("phase-2-ui [expected-red:phase2-ui] two sessions drive the complete authority surface", async ({
  browser,
}) => {
  const coordinator = authority();
  const contextOne = await browser.newContext();
  const contextTwo = await browser.newContext();
  const pageOne = await contextOne.newPage();
  const pageTwo = await contextTwo.newPage();

  try {
    await mount(pageOne, coordinator, { actor: "engineer", session: "ui-a", locale: "en" });
    await mount(pageTwo, coordinator, { actor: "engineer_two", session: "ui-b", locale: "de" });

    await expectNoProhibitedEffects(pageOne);
    await expectNoProhibitedEffects(pageTwo);
    expect(await scanSeededSecrets(pageOne)).toEqual([]);
    expect(await scanSeededSecrets(pageTwo)).toEqual([]);
    const ledger = await readEffectLedger(pageOne);
    console.log(formatEffectLedger("PHASE2_UI_EFFECTS ", ledger));

    const required = [
      ["authority state bar", "glt-flow-card-authority-bar"],
      ["lease control", "glt-flow-card-lease-control"],
      ["conflict recovery", "glt-flow-card-conflict-recovery"],
      ["configured control confirmation", "glt-flow-card-control-confirm"],
      ["trusted evidence view", "glt-flow-card-evidence-view"],
    ];
    const gaps = [];
    for (const [label, tag] of required) {
      const present = await pageOne.evaluate((name) => Boolean(customElements.get(name)), tag);
      if (!present) gaps.push(`${label} (${tag}) is not part of the generated artifact`);
    }

    if (gaps.length > 0) {
      console.log("EXPECTED_RED[phase2-ui]: complete exact-dist Phase-2 UI is unavailable");
      for (const gap of gaps) console.log(`  ui gap: ${gap}`);
    }
    expect(gaps, "complete exact-dist Phase-2 UI is unavailable").toEqual([]);
  } finally {
    await contextOne.close();
    await contextTwo.close();
  }
});
