
/**
 * One catalog string, read off the SDK at call time.
 *
 * This file is concatenated before the v1 bundle, or loaded beside it, so it
 * cannot import the catalog. It reaches the same lookup the rest of the product
 * uses through `window.GLTFlowCardSDK` — one source for a string, because two
 * sources is how a screen ends up disagreeing with itself.
 *
 * The language comes from Home Assistant rather than `navigator.language`,
 * which on a shared control-room workstation is whoever installed it. Falling
 * back to the key rather than to a German sentence: a raw key on screen is
 * visibly wrong, where a German sentence in an English interface looks
 * deliberate.
 */
function gltText(key) {
  const sdk = typeof window === "undefined" ? null : window.GLTFlowCardSDK;
  if (!sdk?.text) return key;
  try {
    const hass = sdk.currentHass?.() ?? null;
    const language = hass?.locale?.language;
    return sdk.text(key, String(language ?? "de").toLowerCase().startsWith("en") ? "en" : "de");
  } catch (_err) {
    return key;
  }
}

import YAML from "../vendor/js-yaml.mjs";

const SYMBOLS=[
["Heizung","heat_pump_neo","Wärmepumpe · Neo","heat_pump"],["Heizung","heat_pump_compact","Wärmepumpe · Kompakt","heat_pump"],["Heizung","buffer_layered","Schichtspeicher","tank"],["Heizung","dhw_tank","Warmwasserspeicher","tank"],["Heizung","boiler","Heizkessel","boiler"],["Heizung","burner","Brenner","generic"],["Heizung","immersion_heater","Heizstab","generic"],["Heizung","underfloor","Fußbodenheizung","room"],["Heizung","radiator","Heizkörper","room"],
["Hydraulik","pump_inline","Pumpe · Inline","pump"],["Hydraulik","pump_twin","Doppelpumpe","pump"],["Hydraulik","pump_variable","Pumpe · FU geregelt","pump"],["Hydraulik","valve_2way","2-Wege-Ventil","valve"],["Hydraulik","valve_3way","3-Wege-Ventil","valve"],["Hydraulik","mixing_valve","3-Wege-Mischer + Antrieb","valve"],["Hydraulik","shutoff_valve","Absperrventil","valve"],["Hydraulik","check_valve","Rückschlagventil","valve"],["Hydraulik","safety_valve","Sicherheitsventil","valve"],["Hydraulik","hydraulic_separator","Hydraulische Weiche","heat_exchanger"],["Hydraulik","heat_exchanger_plate","Plattenwärmetauscher","heat_exchanger"],["Hydraulik","manifold","Verteiler / Sammler","generic"],["Hydraulik","filter_water","Schmutzfänger","generic"],["Hydraulik","dirt_separator","Schlamm-/Magnetitabscheider","generic"],["Hydraulik","expansion_vessel","Ausdehnungsgefäß","tank"],
[gltText("legacy.category_air"),"ahu","RLT-Zentrale","ahu"],[gltText("legacy.category_air"),"fan_supply","Zuluftventilator","fan"],[gltText("legacy.category_air"),"fan_extract","Abluftventilator","fan"],[gltText("legacy.category_air"),"damper","Luftklappe","valve"],[gltText("legacy.category_air"),"fire_damper","Brandschutzklappe","valve"],[gltText("legacy.category_air"),"air_filter","Luftfilter","generic"],[gltText("legacy.category_air"),"heating_coil","Heizregister","heat_exchanger"],[gltText("legacy.category_air"),"cooling_coil","Kühlregister","heat_exchanger"],[gltText("legacy.category_air"),"heat_recovery_rotary","Rotations-WRG","heat_exchanger"],[gltText("legacy.category_air"),"heat_recovery_plate","Platten-WRG","heat_exchanger"],[gltText("legacy.category_air"),"humidifier","Befeuchter","generic"],[gltText("legacy.category_air"),"silencer","Schalldämpfer","generic"],
[gltText("legacy.category_cooling"),"chiller","Kältemaschine","heat_pump"],[gltText("legacy.category_cooling"),"compressor","Verdichter","generic"],[gltText("legacy.category_cooling"),"cooling_tower","Kühlturm","generic"],[gltText("legacy.category_cooling"),"cooling_buffer","Kältepuffer","tank"],
["Energie","pv_array","PV-Feld","pv"],["Energie","inverter","Wechselrichter","generic"],["Energie","battery","Batteriespeicher","generic"],["Energie","grid","Stromnetz","grid"],["Energie","meter","Energiezähler","meter"],["Energie","wallbox","Wallbox","generic"],
["Sensorik","temp_sensor","Temperaturfühler","meter"],["Sensorik","pressure_sensor","Drucksensor","meter"],["Sensorik","dp_sensor","Differenzdruck","meter"],["Sensorik","flow_sensor","Volumenstrom","meter"],["Sensorik","humidity_sensor","Feuchtefühler","meter"],["Sensorik","co2_sensor","CO₂-Sensor","meter"],["Sensorik","frost_thermostat","Frostschutzthermostat","meter"],["Sensorik","room_sensor","Raumsensor","room"],
["Allgemein","generic_machine","Allgemeine Anlage","generic"],["Allgemein","custom_image","Eigenes Symbol / Bild","image"]
].map(([category,id,label,type])=>({category,id,label,type}));

const $=s=>document.querySelector(s),canvas=$("#canvas"),stage=$("#stage"),insp=$("#inspector"),dlg=$("#dialog");
const uid=p=>`${p}_${Math.random().toString(36).slice(2,8)}`;
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
let selected=null,zoom=.7,drag=null,operate=false;

function demoConfig(){return {type:"custom:glt-flow-card",title:"iDM Heizzentrale · Detaildemo",appearance:{mode:"neo2030",show_switch:true},canvas:{width:1600,height:900,viewport_height:650,grid:true},views:[{id:"schematic",name:"Anlagenschema",kind:"schematic"}],equipment:[
{id:"source",type:"generic",symbol:"generic_machine",name:"Wärmequelle",subtitle:"Erdsonde",x:80,y:280,width:190,height:120,preview_value:"8,7 °C",fields:[]},
{id:"p_source",type:"pump",symbol:"pump_variable",name:"Quellenpumpe P-01",x:300,y:315,width:170,height:100,entity:"fan.quellenpumpe",tap_action:"control",sim_active:true,preview_value:"62 %"},
{id:"hp",type:"heat_pump",symbol:"heat_pump_neo",name:"iDM ALM 6-15",x:540,y:245,width:230,height:180,entity:"switch.waermepumpe",tap_action:"control",sim_active:true,preview_value:"8,7 kW",fields:[{label:"Vorlauf",entity:"sensor.idm_vorlauf"},{label:"Rücklauf",entity:"sensor.idm_ruecklauf"}]},
{id:"p_heat",type:"pump",symbol:"pump_inline",name:"Heizkreispumpe P-02",x:815,y:245,width:170,height:100,entity:"switch.heizkreispumpe",tap_action:"control",sim_active:true,preview_value:"83 %"},
{id:"buffer",type:"tank",symbol:"buffer_layered",name:"Pufferspeicher",x:1035,y:210,width:210,height:205,preview_value:"750 l",fields:[{label:"Oben",entity:"sensor.puffer_oben"},{label:"Unten",entity:"sensor.puffer_unten"}]},
{id:"heater",type:"generic",symbol:"immersion_heater",name:"Heizstab EH-01",x:1060,y:475,width:170,height:105,entity:"switch.heizstab",tap_action:"control",sim_active:false,preview_value:"0,0 kW"},
{id:"sep",type:"heat_exchanger",symbol:"hydraulic_separator",name:"Hydraulische Weiche",x:1315,y:250,width:185,height:150,preview_value:"ΔT 4,2 K"},
{id:"mixer",type:"valve",symbol:"mixing_valve",name:"Mischer V-03",x:1305,y:470,width:165,height:105,entity:"number.mischer_hk_d",tap_action:"control",sim_active:true,preview_value:"43 %"},
{id:"hk",type:"room",symbol:"underfloor",name:"Heizkreis D",subtitle:"Fußbodenheizung",x:1260,y:650,width:230,height:150,preview_value:"35,6 °C",fields:[{label:"Raum",entity:"sensor.raum_hk_d"}]},
{id:"dhw",type:"tank",symbol:"dhw_tank",name:"Warmwasser",x:800,y:610,width:210,height:175,preview_value:"49,8 °C"},
{id:"circulation",type:"pump",symbol:"pump_dhw",name:"Zirkulationspumpe P-04",x:1035,y:650,width:175,height:100,entity:"switch.zirkulationspumpe",tap_action:"control",sim_active:false,preview_value:"Aus"},
{id:"hx",type:"heat_exchanger",symbol:"heat_exchanger_plate",name:"Plattenwärmetauscher HX-01",x:555,y:620,width:190,height:135,preview_value:"46,1 °C"},
{id:"exp",type:"tank",symbol:"expansion_vessel",name:"MAG EV-01",x:330,y:630,width:160,height:110,preview_value:"1,7 bar"},
{id:"filter",type:"generic",symbol:"dirt_separator",name:"Schlammabscheider F-01",x:310,y:480,width:190,height:110,preview_value:"OK"}
],paths:[
{id:"source_to_p",from_equipment:"source",to_equipment:"p_source",medium:"source",auto_route:true},{id:"p_to_hp",from_equipment:"p_source",to_equipment:"hp",medium:"source",auto_route:true},
{id:"hp_supply",from_equipment:"hp",to_equipment:"p_heat",medium:"heating_supply",auto_route:true},{id:"p_buffer",from_equipment:"p_heat",to_equipment:"buffer",medium:"heating_supply",auto_route:true},{id:"buffer_sep",from_equipment:"buffer",to_equipment:"sep",medium:"heating_supply",auto_route:true},{id:"sep_mix",from_equipment:"sep",to_equipment:"mixer",medium:"heating_supply",auto_route:true},{id:"mix_hk",from_equipment:"mixer",to_equipment:"hk",medium:"heating_supply",auto_route:true},
{id:"hk_return",from_equipment:"hk",to_equipment:"sep",medium:"heating_return",auto_route:true},{id:"sep_return",from_equipment:"sep",to_equipment:"buffer",medium:"heating_return",auto_route:true},{id:"buffer_return",from_equipment:"buffer",to_equipment:"hp",medium:"heating_return",auto_route:true},
{id:"hp_hx",from_equipment:"hp",to_equipment:"hx",medium:"dhw",auto_route:true},{id:"hx_dhw",from_equipment:"hx",to_equipment:"dhw",medium:"dhw",auto_route:true},{id:"dhw_circ",from_equipment:"dhw",to_equipment:"circulation",medium:"dhw",auto_route:true},{id:"heater_power",from_equipment:"heater",to_equipment:"buffer",medium:"electrical",auto_route:true}
],datapoints:[],kpis:[],alarms:[],assets:[]};}
let cfg=demoConfig();

function symbolSvg(id,active=false){const s=String(id||"");const wrap=(b,c="")=>`<svg viewBox="0 0 64 64" class="sym ${active?"active":""} ${c}">${b}</svg>`;const L=(a,b,c,d,k="")=>`<line x1="${a}" y1="${b}" x2="${c}" y2="${d}" class="${k}"/>`;const C=(a,b,r,k="")=>`<circle cx="${a}" cy="${b}" r="${r}" class="${k}"/>`;const R=(a,b,w,h,r=2,k="")=>`<rect x="${a}" y="${b}" width="${w}" height="${h}" rx="${r}" class="${k}"/>`;const P=(d,k="")=>`<path d="${d}" class="${k}"/>`;
if(s.startsWith("pump"))return wrap(`${C(32,32,20,"body")}${P("M23 43 L23 21 L45 32 Z","accent rotor")}${L(3,32,12,32)}${L(52,32,61,32)}`,"pump");
if(["valve_2way","shutoff_valve"].includes(s))return wrap(`${P("M12 20 L32 32 L12 44 Z","body")}${P("M52 20 L32 32 L52 44 Z","body")}${L(3,32,12,32)}${L(52,32,61,32)}`);
if(["valve_3way","mixing_valve"].includes(s))return wrap(`${P("M9 20 L30 32 L9 44 Z","body")}${P("M51 20 L30 32 L51 44 Z","body")}${P("M21 55 L30 32 L39 55 Z","body")}${s==="mixing_valve"?`${R(24,4,12,10,2,"accentbox")}${L(30,14,30,28,"accent")}`:""}`);
if(s==="check_valve")return wrap(`${P("M14 20 L38 32 L14 44 Z","body")}${L(41,18,41,46,"accent")}`);
if(s==="safety_valve")return wrap(`${P("M16 28 L34 38 L16 48 Z","body")}${L(36,24,36,52,"accent")}${P("M36 24 C44 20 44 13 53 10","accent")}`);
if(s==="hydraulic_separator")return wrap(`${R(22,6,20,52,8,"body")}${L(3,19,22,19,"hot")}${L(42,19,61,19,"hot")}${L(3,45,22,45,"cold")}${L(42,45,61,45,"cold")}${P("M29 14 C40 23 24 34 37 48","accent")}`);
if(["heat_exchanger_plate","heat_recovery_plate"].includes(s))return wrap(`${R(13,8,38,48,2,"body")}${P("M19 14 L45 50 M45 14 L19 50 M25 10 L25 54 M39 10 L39 54","thin")}`);
if(s==="manifold")return wrap(`${R(10,24,44,16,5,"body")}${[15,24,33,42,51].map(x=>`${L(x,12,x,24)}${L(x,40,x,52)}`).join("")}`);
if(["filter_water","dirt_separator","air_filter"].includes(s))return wrap(`${R(14,12,36,40,2,"body")}${P("M17 48 L47 16 M24 50 L50 24 M14 40 L40 14","thin")}`);
if(s==="expansion_vessel")return wrap(`${C(32,32,23,"body")}${P("M10 32 Q32 21 54 32 Q32 43 10 32","accent")}${L(32,55,32,62)}`);
if(["buffer_layered","cooling_buffer"].includes(s))return wrap(`${P("M18 9 Q18 4 32 4 Q46 4 46 9 L46 55 Q46 60 32 60 Q18 60 18 55 Z","body")}${R(20,10,24,20,0,"hotfill")}${R(20,34,24,20,0,"coldfill")}`);
if(s==="dhw_tank")return wrap(`${P("M18 9 Q18 4 32 4 Q46 4 46 9 L46 55 Q46 60 32 60 Q18 60 18 55 Z","body")}${P("M24 43 C24 34 40 34 40 26 C40 18 24 18 24 11","accent")}`);
if(s==="immersion_heater")return wrap(`${R(14,12,36,40,3,"body")}${P("M20 40 L26 23 L32 40 L38 23 L44 40","power")}`);
if(s==="boiler")return wrap(`${R(12,9,40,46,7,"body")}${P("M32 47 C20 39 24 28 32 19 C40 28 44 39 32 47 Z","flame")}`);
if(s==="burner")return wrap(`${R(9,20,46,25,4,"body")}${C(22,32,8,"accent")}${P("M30 32 L48 24 L48 40 Z","flame")}`);
if(["underfloor","radiator"].includes(s))return s==="underfloor"?wrap(`${R(8,12,48,40,4,"body")}${P("M14 39 C18 20 25 20 29 39 C33 20 40 20 50 39","hot")}`):wrap(`${R(8,14,48,36,4,"body")}${[16,24,32,40,48].map(x=>L(x,18,x,46,"thin")).join("")}`);
if(s.startsWith("fan"))return wrap(`${C(32,32,22,"body")}${P("M32 31 C31 18 38 12 45 15 C45 23 40 29 33 32 M33 33 C45 35 49 42 44 48 C36 46 32 40 32 34 M31 33 C23 44 15 45 11 38 C15 31 22 29 30 32","accent rotor")}`,"fan");
if(["damper","fire_damper"].includes(s))return wrap(`${R(7,18,50,28,1,"body")}${L(12,42,52,22,s==="fire_damper"?"alarm":"accent")}${C(32,32,3,"accent")}`);
if(["heating_coil","cooling_coil"].includes(s))return wrap(`${R(9,12,46,40,2,"body")}${P("M16 42 C23 42 18 22 26 22 C34 22 29 42 37 42 C45 42 40 22 48 22",s==="cooling_coil"?"cold":"hot")}`);
if(s==="heat_recovery_rotary")return wrap(`${C(32,32,22,"body")}${P("M32 11 L32 53 M11 32 L53 32 M17 17 L47 47 M47 17 L17 47","thin")}${C(32,32,5,"accent rotor")}`,"fan");
if(s==="humidifier")return wrap(`${R(9,14,46,36,2,"body")}${P("M21 41 C13 31 21 22 21 22 C21 22 29 31 21 41 Z M37 42 C29 33 37 24 37 24 C37 24 45 33 37 42 Z","accent")}`);
if(s==="silencer")return wrap(`${R(7,16,50,32,2,"body")}${[15,23,31,39,47].map(x=>L(x,19,x+6,45,"thin")).join("")}`);
if(["heat_pump_neo","heat_pump_compact","chiller"].includes(s))return wrap(`${R(10,7,44,50,8,"body")}${C(32,32,14,"accent")}${P("M23 34 C26 24 38 24 41 34 M22 39 L42 39","thin")}`);
if(s==="compressor")return wrap(`${C(32,32,23,"body")}${P("M20 40 C25 22 41 20 45 32 C48 42 31 49 24 36","accent")}`);
if(s==="cooling_tower")return wrap(`${P("M18 8 L46 8 L52 56 L12 56 Z","body")}${P("M18 24 C26 18 38 18 46 24 M15 39 C25 33 39 33 49 39","cold")}`);
if(s==="pv_array")return wrap(`${P("M10 20 L48 12 L55 44 L17 52 Z","body")}${L(16,31,52,23,"thin")}${L(18,42,54,34,"thin")}${P("M8 9 L13 14 M3 20 L10 21 M19 3 L20 10","power")}`);
if(s==="inverter")return wrap(`${R(10,12,44,40,6,"body")}${P("M16 31 C21 22 27 40 32 31 C37 22 43 40 48 31","accent")}`);
if(s==="battery")return wrap(`${R(12,15,40,34,5,"body")}${R(26,9,12,6,2,"body")}${R(17,21,30,22,3,"goodfill")}`);
if(s==="grid")return wrap(`${L(32,5,32,59,"body")}${L(18,20,46,20,"body")}${L(13,35,51,35,"body")}${L(18,20,9,59,"thin")}${L(46,20,55,59,"thin")}${L(32,20,18,59,"thin")}${L(32,20,46,59,"thin")}`);
if(["meter","temp_sensor","pressure_sensor","dp_sensor","flow_sensor","humidity_sensor","co2_sensor","frost_thermostat","room_sensor"].includes(s)){const t=s==="temp_sensor"?"T":s==="pressure_sensor"?"P":s==="dp_sensor"?"ΔP":s==="flow_sensor"?"F":s==="humidity_sensor"?"%":s==="co2_sensor"?"CO₂":s==="frost_thermostat"?"FROST":"M";return wrap(`${C(32,32,22,"body")}<text x="32" y="36" text-anchor="middle">${t}</text>`)}
return wrap(`${R(11,11,42,42,8,"body")}${P("M20 38 L32 20 L44 38 Z","accent")}`)}

function status(t){$("#status").textContent=t;clearTimeout(status.timer);status.timer=setTimeout(()=>$("#status").textContent="",1800)}
function saveDraft(){localStorage.setItem("glt-online.autosave",JSON.stringify({at:new Date().toISOString(),config:cfg}))}
function saveLocal(name=cfg.title){const list=JSON.parse(localStorage.getItem("glt-online.projects")||"[]").filter(p=>p.id!==cfg.project?.id);const id=cfg.project?.id||uid("project");cfg.project={id,name};list.unshift({id,name,updated:new Date().toISOString(),config:structuredClone(cfg)});localStorage.setItem("glt-online.projects",JSON.stringify(list.slice(0,50)));status("Projekt gespeichert")}
function symById(id){return SYMBOLS.find(s=>s.id===id)||SYMBOLS.find(s=>s.type===id)||SYMBOLS[0]}
function renderPalette(){const q=$("#search").value.toLowerCase(),groups=[...new Set(SYMBOLS.map(s=>s.category))];$("#palette").innerHTML=groups.map(g=>{const a=SYMBOLS.filter(s=>s.category===g&&(!q||`${s.id} ${s.label} ${s.category}`.toLowerCase().includes(q)));return a.length?`<div class="group">${g}</div>${a.map(s=>`<div class="item" draggable="true" data-symbol="${s.id}"><i>${symbolSvg(s.id)}</i><span><b>${s.label}</b><small>${s.id}</small></span></div>`).join("")}`:""}).join("");document.querySelectorAll(".item").forEach(i=>i.ondragstart=e=>e.dataTransfer.setData("text/symbol",i.dataset.symbol))}
function render(){document.body.dataset.theme=cfg.appearance?.mode||"neo2030";$("#appearance").value=cfg.appearance?.mode||"neo2030";canvas.classList.toggle("operate",operate);canvas.style.width=`${cfg.canvas.width}px`;canvas.style.height=`${cfg.canvas.height}px`;canvas.style.transform=`scale(${zoom})`;canvas.innerHTML="";cfg.paths.forEach(drawPipe);cfg.equipment.forEach(drawNode);renderInspector()}
function center(e,side="right"){const x=e.x||0,y=e.y||0,w=e.width||190,h=e.height||110;if(side==="left")return[x,y+h/2];if(side==="top")return[x+w/2,y];if(side==="bottom")return[x+w/2,y+h];return[x+w,y+h/2]}
function drawPipe(p){if(!p.from_equipment||!p.to_equipment)return;const a=cfg.equipment.find(x=>x.id===p.from_equipment),b=cfg.equipment.find(x=>x.id===p.to_equipment);if(!a||!b)return;const [x1,y1]=center(a,"right"),[x2,y2]=center(b,"left"),mid=Math.round((x1+x2)/2/10)*10;[[x1,y1,mid,y1],[mid,y1,mid,y2],[mid,y2,x2,y2]].forEach(([ax,ay,bx,by])=>{const line=document.createElement("div"),len=Math.hypot(bx-ax,by-ay),ang=Math.atan2(by-ay,bx-ax)*180/Math.PI;line.className=`pipe medium-${p.medium||"neutral"}`;line.style.left=`${ax}px`;line.style.top=`${ay}px`;line.style.width=`${len}px`;line.style.transform=`rotate(${ang}deg)`;canvas.appendChild(line)})}
function drawNode(e){const n=document.createElement("div"),sym=symById(e.symbol||e.type);n.className="node"+(selected===e.id?" sel":"")+(e.sim_active?" is-active":"");n.dataset.id=e.id;n.style.left=`${e.x||0}px`;n.style.top=`${e.y||0}px`;n.style.width=`${e.width||200}px`;n.style.height=`${e.height||120}px`;n.innerHTML=`<div class="machine-icon">${symbolSvg(e.symbol||sym.id,!!e.sim_active)}</div><div class="machine-copy"><div class="title">${esc(e.name||sym.label)}</div><div class="type">${esc(sym.category)} · ${esc(e.symbol||sym.id)}</div><div class="value">${esc(e.preview_value||e.entity||"Entity in HA zuordnen")}</div></div><span class="state-dot ${e.sim_active?"on":""}"></span>`;n.onclick=ev=>{ev.stopPropagation();if(operate){showOperate(e);return}selected=e.id;render()};n.onpointerdown=ev=>{if(operate||ev.button!==0)return;selected=e.id;drag={id:e.id,sx:ev.clientX,sy:ev.clientY,x:e.x||0,y:e.y||0};window.onpointermove=move;window.onpointerup=()=>{drag=null;window.onpointermove=null;window.onpointerup=null;saveDraft()}};canvas.appendChild(n)}
function move(ev){if(!drag)return;const e=cfg.equipment.find(x=>x.id===drag.id);e.x=Math.round((drag.x+(ev.clientX-drag.sx)/zoom)/10)*10;e.y=Math.round((drag.y+(ev.clientY-drag.sy)/zoom)/10)*10;render()}
function renderInspector(){const e=cfg.equipment.find(x=>x.id===selected);if(!e){insp.innerHTML=`<div class="empty-inspector"><b>${operate?"Bedienvorschau aktiv":"Kein Bauteil ausgewählt"}</b><p>${operate?"Bauteil anklicken: simulierte Objektbedienung öffnet sich.":"Links ein Detailbauteil auf die Zeichenfläche ziehen oder vorhandenes Objekt anklicken."}</p></div>`;return}const action=typeof e.tap_action==="string"?e.tap_action:e.tap_action?.action||"control";insp.innerHTML=`<div class="selected-preview">${symbolSvg(e.symbol,!!e.sim_active)}<div><b>${esc(e.name)}</b><small>${esc(e.id)}</small></div></div><div class="field"><label>Name</label><input data-f="name" value="${esc(e.name||"")}"></div><div class="field"><label>Haupt-Entity</label><input data-f="entity" value="${esc(e.entity||"")}" placeholder="switch.pumpe"></div><div class="field"><label>Status-Entity</label><input data-f="state_entity" value="${esc(e.state_entity||"")}" placeholder="binary_sensor.pumpe_laeuft"></div><div class="field"><label>Steuer-Entity</label><input data-f="control_entity" value="${esc(e.control_entity||"")}" placeholder="optional, sonst Haupt-Entity"></div><div class="field"><label>Detail-Symbol</label><select data-f="symbol">${SYMBOLS.map(s=>`<option value="${s.id}" ${s.id===e.symbol?"selected":""}>${s.category} · ${s.label}</option>`).join("")}</select></div><div class="field"><label>Aktion bei Klick</label><select id="tap"><option value="control">Objektbedienung öffnen</option><option value="more-info">HA Mehr-Info</option><option value="toggle">Direkt umschalten</option><option value="call-service">Service aufrufen</option><option value="none">Keine Aktion</option></select></div><div class="field"><label>Vorschauwert</label><input data-f="preview_value" value="${esc(e.preview_value||"")}" placeholder="z. B. 83 %"></div><div class="field"><label>X / Y</label><div class="two"><input data-f="x" type="number" value="${e.x||0}"><input data-f="y" type="number" value="${e.y||0}"></div></div><div class="field"><label>Breite / Höhe</label><div class="two"><input data-f="width" type="number" value="${e.width||200}"><input data-f="height" type="number" value="${e.height||120}"></div></div><div class="actions"><button id="connect">Verbinden…</button><button id="dup">Duplizieren</button><button id="del">Löschen</button></div>`;$("#tap").value=action;$("#tap").onchange=()=>{e.tap_action=$("#tap").value;saveDraft()};insp.querySelectorAll("[data-f]").forEach(i=>i.onchange=()=>{e[i.dataset.f]=i.type==="number"?+i.value:i.value;render();saveDraft()});$("#del").onclick=()=>{cfg.equipment=cfg.equipment.filter(x=>x.id!==e.id);cfg.paths=cfg.paths.filter(p=>p.from_equipment!==e.id&&p.to_equipment!==e.id);selected=null;render();saveDraft()};$("#dup").onclick=()=>{const n=structuredClone(e);n.id=uid(e.type||"eq");n.x=(n.x||0)+40;n.y=(n.y||0)+40;cfg.equipment.push(n);selected=n.id;render();saveDraft()};$("#connect").onclick=()=>showConnect(e)}
function showDialog(title,html){$("#dialog-title").textContent=title;$("#dialog-body").innerHTML=html;dlg.showModal()}$("#dialog-close").onclick=()=>dlg.close();
function showConnect(from){showDialog(gltText("legacy.auto_connect"),`<div class="field"><label>Ziel</label><select id="target">${cfg.equipment.filter(x=>x.id!==from.id).map(x=>`<option value="${x.id}">${esc(x.name||x.id)}</option>`).join("")}</select></div><div class="field"><label>Medium</label><select id="medium"><option value="heating_supply">Vorlauf</option><option value="heating_return">Rücklauf</option><option value="source">Wärmequelle</option><option value="dhw">Warmwasser</option><option value="cooling_supply">Kälte Vorlauf</option><option value="cooling_return">Kälte Rücklauf</option><option value="air_supply">Zuluft</option><option value="air_extract">Abluft</option><option value="electrical">Elektrisch</option></select></div><button id="do-connect">Orthogonal verbinden</button>`);$("#do-connect").onclick=()=>{cfg.paths.push({id:uid("path"),from_equipment:from.id,to_equipment:$("#target").value,medium:$("#medium").value,auto_route:true,width:8});dlg.close();render();saveDraft()}}
function showOperate(e){const sym=symById(e.symbol),isOn=!!e.sim_active;showDialog(`Objektbedienung · ${e.name}`,`<div class="operate-head">${symbolSvg(e.symbol,isOn)}<div><b>${esc(e.name)}</b><small>${esc(e.control_entity||e.entity||"Home Assistant Entity")}</small></div><span class="op-state ${isOn?"on":""}">${isOn?"AKTIV":"AUS"}</span></div><div class="operate-values"><div><small>Status</small><b>${isOn?"Ein / Betrieb":"Aus / Bereit"}</b></div><div><small>Aktueller Wert</small><b>${esc(e.preview_value||"–")}</b></div><div><small>Symbol</small><b>${esc(sym.label)}</b></div></div><div class="actions"><button id="op-on">Ein</button><button id="op-off">Aus</button><button id="op-toggle">Umschalten</button><button id="op-more">HA Mehr-Info</button></div><p class="hint">Online nur Simulation. In Home Assistant ruft die Card echte HA-Services auf; Viewer/Operator/Designer-Rechte und Bestätigungen werden berücksichtigt.</p>`);const set=v=>{e.sim_active=v;e.preview_value=v?(e.preview_value==="Aus"?"Ein":e.preview_value):"Aus";dlg.close();render();saveDraft()};$("#op-on").onclick=()=>set(true);$("#op-off").onclick=()=>set(false);$("#op-toggle").onclick=()=>set(!isOn);$("#op-more").onclick=()=>status("In HA öffnet sich die Entity-/Objektbedienung")}
canvas.ondragover=e=>e.preventDefault();canvas.ondrop=e=>{e.preventDefault();const symbol=e.dataTransfer.getData("text/symbol"),sym=symById(symbol),r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/zoom,y=(e.clientY-r.top)/zoom,id=uid(sym.type||"eq"),small=["pump","valve","meter"].includes(sym.type);cfg.equipment.push({id,type:sym.type,name:sym.label,symbol:sym.id,x:Math.round(x/10)*10,y:Math.round(y/10)*10,width:small?170:220,height:small?100:135,fields:[],tap_action:"control",sim_active:false});selected=id;render();saveDraft()};canvas.onclick=()=>{selected=null;render()};
$("#search").oninput=renderPalette;$("#new").onclick=()=>{if(confirm("Neues Projekt starten?")){cfg={...demoConfig(),title:"GLT Projekt",project:{},equipment:[],paths:[],datapoints:[],kpis:[],alarms:[],assets:[]};selected=null;render();saveDraft()}};$("#save").onclick=()=>{const name=prompt(gltText("legacy.prompt_project_name"),cfg.project?.name||cfg.title);if(name){cfg.title=name;saveLocal(name);render()}};$("#open").onclick=()=>{const list=JSON.parse(localStorage.getItem("glt-online.projects")||"[]");showDialog("Projektbibliothek",list.map(p=>`<div class="project"><b>${esc(p.name)}</b><small>${new Date(p.updated).toLocaleString()}</small><button data-load="${p.id}">Laden</button></div>`).join("")||"Noch keine Projekte.");document.querySelectorAll("[data-load]").forEach(b=>b.onclick=()=>{const p=list.find(x=>x.id===b.dataset.load);cfg=structuredClone(p.config);selected=null;dlg.close();render()})};$("#export").onclick=()=>{const y=YAML.dump(cfg,{noRefs:true,lineWidth:120});showDialog(gltText("legacy.lovelace_yaml"),`<textarea id="yaml">${esc(y)}</textarea><div class="actions"><button id="copy">Kopieren</button><button id="download">Download</button></div>`);$("#copy").onclick=()=>navigator.clipboard.writeText($("#yaml").value);$("#download").onclick=()=>{const blob=new Blob([$("#yaml").value],{type:"application/yaml"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${cfg.project?.name||"glt-project"}.yaml`;a.click()}};$("#import").onclick=()=>{showDialog("YAML Import",'<textarea id="yaml" placeholder="type: custom:glt-flow-card"></textarea><button id="load-yaml">Importieren</button><div id="err"></div>');$("#load-yaml").onclick=()=>{try{const v=YAML.load($("#yaml").value);if(!v||typeof v!=="object")throw Error("Ungültige YAML");cfg=v;cfg.appearance=cfg.appearance||{mode:"neo2030"};cfg.canvas=cfg.canvas||{width:1600,height:900};cfg.equipment=cfg.equipment||[];cfg.paths=cfg.paths||[];cfg.datapoints=cfg.datapoints||[];cfg.kpis=cfg.kpis||[];selected=null;dlg.close();render();saveDraft()}catch(err){$("#err").textContent=err.message}}};$("#fit").onclick=()=>{zoom=Math.min((stage.clientWidth-60)/cfg.canvas.width,(stage.clientHeight-60)/cfg.canvas.height,.95);render()};$("#preview").onclick=()=>{operate=!operate;$("#preview").classList.toggle("active",operate);$("#preview").textContent=operate?"■ Editor-Modus":"▶ Bedienvorschau";selected=null;render()};$("#appearance").onchange=e=>{cfg.appearance=cfg.appearance||{};cfg.appearance.mode=e.target.value;render();saveDraft()};
renderPalette();const auto=JSON.parse(localStorage.getItem("glt-online.autosave")||"null");if(auto?.config&&confirm("Letzten automatisch gespeicherten Entwurf laden?"))cfg=auto.config;render();$("#fit").click();
